-- Resident Training & Assessment v1.0.68
-- Prior Experience Logbook
-- - Resident editable draft before final submission
-- - Two senior-resident approvals first
-- - Then intervention-scoped assessor verification
-- - Assessor comments + approve/reject
-- - Reconsideration workflow for senior/assessor rejections
-- - Owner assignment of assessors to intervention scopes

begin;

create table if not exists public.prior_experience_logbooks (
  id bigint generated by default as identity primary key,
  resident_id uuid not null unique references public.profiles(id) on delete cascade,
  status text not null default 'draft',
  senior_1_id uuid references public.profiles(id),
  senior_2_id uuid references public.profiles(id),
  resident_notes text,
  submitted_at timestamptz,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prior_experience_logbooks_status_check check (status in ('draft','senior_review','assessor_review','rejected','approved'))
);

create table if not exists public.prior_experience_interventions (
  id bigint generated by default as identity primary key,
  logbook_id bigint not null references public.prior_experience_logbooks(id) on delete cascade,
  intervention_name text not null,
  attended_count integer not null default 0,
  assisted_count integer not null default 0,
  solo_guided_count integer not null default 0,
  solo_unguided_count integer not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(logbook_id, intervention_name),
  constraint prior_experience_interventions_counts_check check (
    attended_count >= 0 and assisted_count >= 0 and solo_guided_count >= 0 and solo_unguided_count >= 0
  )
);

create table if not exists public.prior_experience_conferences (
  id bigint generated by default as identity primary key,
  logbook_id bigint not null references public.prior_experience_logbooks(id) on delete cascade,
  conference_name text not null,
  participation text not null,
  conference_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prior_experience_conferences_participation_check check (participation in ('attended','speaker'))
);

create table if not exists public.prior_experience_senior_reviews (
  id bigint generated by default as identity primary key,
  logbook_id bigint not null references public.prior_experience_logbooks(id) on delete cascade,
  senior_id uuid not null references public.profiles(id),
  status text not null default 'pending',
  note text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(logbook_id, senior_id),
  constraint prior_experience_senior_status_check check (status in ('pending','approved','rejected'))
);

create table if not exists public.prior_experience_assessor_assignments (
  assessor_id uuid not null references public.profiles(id) on delete cascade,
  scope_name text not null,
  is_active boolean not null default true,
  assigned_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  primary key (assessor_id, scope_name)
);

create table if not exists public.prior_experience_scope_reviews (
  id bigint generated by default as identity primary key,
  logbook_id bigint not null references public.prior_experience_logbooks(id) on delete cascade,
  scope_name text not null,
  status text not null default 'pending',
  decided_by uuid references public.profiles(id),
  note text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(logbook_id, scope_name),
  constraint prior_experience_scope_status_check check (status in ('pending','approved','rejected'))
);

create table if not exists public.prior_experience_reconsiderations (
  id bigint generated by default as identity primary key,
  logbook_id bigint not null references public.prior_experience_logbooks(id) on delete cascade,
  review_kind text not null,
  review_id bigint not null,
  reviewer_id uuid not null references public.profiles(id),
  scope_name text,
  resident_reason text not null,
  status text not null default 'requested',
  reviewer_note text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint prior_experience_reconsideration_kind_check check (review_kind in ('senior','assessor')),
  constraint prior_experience_reconsideration_status_check check (status in ('requested','approved','rejected'))
);

create unique index if not exists prior_experience_one_pending_reconsideration_idx
  on public.prior_experience_reconsiderations(review_kind, review_id)
  where status = 'requested';

create index if not exists prior_experience_scope_assignment_idx
  on public.prior_experience_assessor_assignments(scope_name, is_active);
create index if not exists prior_experience_scope_reviews_idx
  on public.prior_experience_scope_reviews(logbook_id, status);
create index if not exists prior_experience_senior_reviews_idx
  on public.prior_experience_senior_reviews(logbook_id, status);

alter table public.prior_experience_logbooks enable row level security;
alter table public.prior_experience_interventions enable row level security;
alter table public.prior_experience_conferences enable row level security;
alter table public.prior_experience_senior_reviews enable row level security;
alter table public.prior_experience_assessor_assignments enable row level security;
alter table public.prior_experience_scope_reviews enable row level security;
alter table public.prior_experience_reconsiderations enable row level security;

revoke all on public.prior_experience_logbooks from public, anon, authenticated;
revoke all on public.prior_experience_interventions from public, anon, authenticated;
revoke all on public.prior_experience_conferences from public, anon, authenticated;
revoke all on public.prior_experience_senior_reviews from public, anon, authenticated;
revoke all on public.prior_experience_assessor_assignments from public, anon, authenticated;
revoke all on public.prior_experience_scope_reviews from public, anon, authenticated;
revoke all on public.prior_experience_reconsiderations from public, anon, authenticated;

-- ------------------------------------------------------------------
-- Internal helper: create one assessor-verification scope per activity.
-- ------------------------------------------------------------------
create or replace function public._prior_experience_ensure_scopes_v1068(p_logbook_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row record;
  v_sender uuid;
begin
  select p.id into v_sender
  from public.profiles p
  where p.role::text = 'owner' and p.is_active = true
  order by p.created_at nulls last
  limit 1;

  for v_row in
    with scopes as (
      select distinct i.intervention_name as scope_name
      from public.prior_experience_interventions i
      where i.logbook_id = p_logbook_id
        and (i.attended_count + i.assisted_count + i.solo_guided_count + i.solo_unguided_count) > 0
      union all
      select 'Conferences'
      where exists (select 1 from public.prior_experience_conferences c where c.logbook_id = p_logbook_id)
    )
    insert into public.prior_experience_scope_reviews(logbook_id, scope_name)
    select p_logbook_id, s.scope_name
    from scopes s
    on conflict (logbook_id, scope_name) do nothing
    returning id, scope_name
  loop
    insert into public.private_messages(sender_id, receiver_id, subject, body)
    select coalesce(v_sender, a.assessor_id), a.assessor_id,
           'Prior experience verification request',
           'A resident Prior Experience Logbook is ready for your verification scope: ' || v_row.scope_name || '. Open Logbook requests to review the evidence, comment, approve or reject.'
    from public.prior_experience_assessor_assignments a
    join public.profiles p on p.id = a.assessor_id and p.role::text = 'assessor' and p.is_active = true
    where a.scope_name = v_row.scope_name and a.is_active = true;
  end loop;
end;
$$;
revoke all on function public._prior_experience_ensure_scopes_v1068(bigint) from public, anon, authenticated;

-- --------------------------------------------------------------
-- Internal helper: derive overall status from current decisions.
-- --------------------------------------------------------------
create or replace function public._prior_experience_recalculate_v1068(p_logbook_id bigint)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_senior_total integer;
  v_senior_approved integer;
  v_senior_rejected integer;
  v_scope_total integer;
  v_scope_approved integer;
  v_scope_rejected integer;
  v_status text;
begin
  select count(*), count(*) filter (where status='approved'), count(*) filter (where status='rejected')
    into v_senior_total, v_senior_approved, v_senior_rejected
  from public.prior_experience_senior_reviews
  where logbook_id = p_logbook_id;

  if v_senior_rejected > 0 then
    v_status := 'rejected';
  elsif v_senior_total < 2 or v_senior_approved < 2 then
    v_status := 'senior_review';
  else
    perform public._prior_experience_ensure_scopes_v1068(p_logbook_id);
    select count(*), count(*) filter (where status='approved'), count(*) filter (where status='rejected')
      into v_scope_total, v_scope_approved, v_scope_rejected
    from public.prior_experience_scope_reviews
    where logbook_id = p_logbook_id;

    if v_scope_rejected > 0 then
      v_status := 'rejected';
    elsif v_scope_total = 0 or v_scope_approved < v_scope_total then
      v_status := 'assessor_review';
    else
      v_status := 'approved';
    end if;
  end if;

  update public.prior_experience_logbooks
     set status = v_status,
         verified_at = case when v_status='approved' then coalesce(verified_at, now()) else null end,
         updated_at = now()
   where id = p_logbook_id;

  return v_status;
end;
$$;
revoke all on function public._prior_experience_recalculate_v1068(bigint) from public, anon, authenticated;

-- --------------------------------------------------------------
-- Resident: eligible senior signatories (higher year; Year 5 uses Year 5 peers because no higher cohort exists).
-- --------------------------------------------------------------
create or replace function public.get_prior_experience_eligible_seniors_v1068()
returns table(id uuid, display_name text, residency_year smallint)
language sql
security definer
set search_path = public
as $$
  select s.id, s.display_name, s.residency_year
  from public.profiles me
  join public.profiles s on s.role::text='resident'
    and s.is_active=true
    and s.id<>me.id
    and (s.residency_year > me.residency_year or (me.residency_year=5 and s.residency_year=5))
  where me.id=auth.uid() and me.role::text='resident' and me.is_active=true
  order by s.residency_year, s.display_name;
$$;
revoke all on function public.get_prior_experience_eligible_seniors_v1068() from public, anon;
grant execute on function public.get_prior_experience_eligible_seniors_v1068() to authenticated;

-- --------------------------------------------------------------
-- Read one submission, with authorization for every workflow role.
-- --------------------------------------------------------------
create or replace function public.get_prior_experience_submission_v1068(p_logbook_id bigint default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_logbook_id bigint;
  v_header jsonb;
begin
  select p.role::text into v_role from public.profiles p where p.id=v_uid and p.is_active=true;
  if v_role is null then raise exception 'Active account required'; end if;

  if p_logbook_id is null then
    if v_role <> 'resident' then return null; end if;
    select l.id into v_logbook_id from public.prior_experience_logbooks l where l.resident_id=v_uid;
    if v_logbook_id is null then return null; end if;
  else
    v_logbook_id := p_logbook_id;
  end if;

  if not exists (
    select 1 from public.prior_experience_logbooks l
    where l.id=v_logbook_id and (
      v_role='owner'
      or l.resident_id=v_uid
      or l.senior_1_id=v_uid
      or l.senior_2_id=v_uid
      or exists (
        select 1 from public.prior_experience_scope_reviews sr
        join public.prior_experience_assessor_assignments aa on aa.scope_name=sr.scope_name and aa.assessor_id=v_uid and aa.is_active=true
        where sr.logbook_id=l.id
      )
      or exists (
        select 1 from public.prior_experience_reconsiderations r
        where r.logbook_id=l.id and r.reviewer_id=v_uid
      )
    )
  ) then raise exception 'You cannot view this Prior Experience Logbook'; end if;

  select jsonb_build_object(
    'id', l.id,
    'resident_id', l.resident_id,
    'resident_name', rp.display_name,
    'residency_year', rp.residency_year,
    'status', l.status,
    'senior_1_id', l.senior_1_id,
    'senior_2_id', l.senior_2_id,
    'senior_1_name', s1.display_name,
    'senior_2_name', s2.display_name,
    'resident_notes', l.resident_notes,
    'submitted_at', l.submitted_at,
    'verified_at', l.verified_at,
    'editable', (l.resident_id=v_uid and l.status='draft')
  ) into v_header
  from public.prior_experience_logbooks l
  join public.profiles rp on rp.id=l.resident_id
  left join public.profiles s1 on s1.id=l.senior_1_id
  left join public.profiles s2 on s2.id=l.senior_2_id
  where l.id=v_logbook_id;

  return jsonb_build_object(
    'header', v_header,
    'interventions', coalesce((select jsonb_agg(jsonb_build_object(
      'id',i.id,'intervention_name',i.intervention_name,'attended_count',i.attended_count,
      'assisted_count',i.assisted_count,'solo_guided_count',i.solo_guided_count,
      'solo_unguided_count',i.solo_unguided_count,'notes',i.notes
    ) order by i.id) from public.prior_experience_interventions i where i.logbook_id=v_logbook_id), '[]'::jsonb),
    'conferences', coalesce((select jsonb_agg(jsonb_build_object(
      'id',c.id,'conference_name',c.conference_name,'participation',c.participation,
      'conference_date',c.conference_date,'notes',c.notes
    ) order by c.id) from public.prior_experience_conferences c where c.logbook_id=v_logbook_id), '[]'::jsonb),
    'senior_reviews', coalesce((select jsonb_agg(jsonb_build_object(
      'id',sr.id,'senior_id',sr.senior_id,'senior_name',p.display_name,'status',sr.status,
      'note',sr.note,'decided_at',sr.decided_at
    ) order by sr.id) from public.prior_experience_senior_reviews sr join public.profiles p on p.id=sr.senior_id where sr.logbook_id=v_logbook_id), '[]'::jsonb),
    'scope_reviews', coalesce((select jsonb_agg(jsonb_build_object(
      'id',sc.id,'scope_name',sc.scope_name,'status',sc.status,'decided_by',sc.decided_by,
      'assessor_name',p.display_name,'note',sc.note,'decided_at',sc.decided_at
    ) order by sc.scope_name) from public.prior_experience_scope_reviews sc left join public.profiles p on p.id=sc.decided_by where sc.logbook_id=v_logbook_id), '[]'::jsonb),
    'reconsiderations', coalesce((select jsonb_agg(jsonb_build_object(
      'id',r.id,'review_kind',r.review_kind,'review_id',r.review_id,'reviewer_id',r.reviewer_id,
      'reviewer_name',p.display_name,'scope_name',r.scope_name,'resident_reason',r.resident_reason,
      'status',r.status,'reviewer_note',r.reviewer_note,'created_at',r.created_at,'resolved_at',r.resolved_at
    ) order by r.created_at) from public.prior_experience_reconsiderations r join public.profiles p on p.id=r.reviewer_id where r.logbook_id=v_logbook_id), '[]'::jsonb)
  );
end;
$$;
revoke all on function public.get_prior_experience_submission_v1068(bigint) from public, anon;
grant execute on function public.get_prior_experience_submission_v1068(bigint) to authenticated;

-- --------------------------------------------------------------
-- Resident: save/replace draft content before final submission.
-- --------------------------------------------------------------
create or replace function public.save_prior_experience_draft_v1068(
  p_senior_1_id uuid,
  p_senior_2_id uuid,
  p_interventions jsonb,
  p_conferences jsonb,
  p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_logbook public.prior_experience_logbooks%rowtype;
  v_item jsonb;
  v_name text;
  v_attended integer;
  v_assisted integer;
  v_guided integer;
  v_unguided integer;
  v_allowed text[] := array[
    'CVP','Intubation','Temporary pacemaker','Permanent pacemaker implantation','Pacemaker programming',
    'ICD implantation','CRT implantation','Pericardiocentesis','TEE','DSE','Coronary angiography',
    'Elective PCI','Primary PCI','IVUS','Rotablation','TAVI','ASD closure','Mitral balloon valvotomy',
    'Exercise stress ECG','Tilting table','Nuclear imaging','CT CA','CMR','CPR'
  ];
begin
  if not exists (select 1 from public.profiles p where p.id=v_uid and p.role::text='resident' and p.is_active=true) then
    raise exception 'Active Resident account required';
  end if;

  insert into public.prior_experience_logbooks(resident_id)
  values (v_uid)
  on conflict (resident_id) do nothing;

  select * into v_logbook from public.prior_experience_logbooks where resident_id=v_uid for update;
  if v_logbook.status <> 'draft' then raise exception 'This Prior Experience Logbook has already been finally submitted and is locked'; end if;
  if p_senior_1_id is not null and p_senior_2_id is not null and p_senior_1_id=p_senior_2_id then raise exception 'Choose two different senior residents'; end if;

  update public.prior_experience_logbooks
     set senior_1_id=p_senior_1_id, senior_2_id=p_senior_2_id, resident_notes=nullif(btrim(coalesce(p_notes,'')),''), updated_at=now()
   where id=v_logbook.id;

  delete from public.prior_experience_interventions where logbook_id=v_logbook.id;
  delete from public.prior_experience_conferences where logbook_id=v_logbook.id;

  for v_item in select value from jsonb_array_elements(coalesce(p_interventions,'[]'::jsonb))
  loop
    v_name := btrim(coalesce(v_item->>'intervention_name',''));
    v_attended := greatest(coalesce((v_item->>'attended_count')::integer,0),0);
    v_assisted := greatest(coalesce((v_item->>'assisted_count')::integer,0),0);
    v_guided := greatest(coalesce((v_item->>'solo_guided_count')::integer,0),0);
    v_unguided := greatest(coalesce((v_item->>'solo_unguided_count')::integer,0),0);
    if v_name = '' or not (v_name = any(v_allowed)) then raise exception 'Unsupported intervention: %', v_name; end if;
    if (v_attended+v_assisted+v_guided+v_unguided) > 0 then
      insert into public.prior_experience_interventions(logbook_id,intervention_name,attended_count,assisted_count,solo_guided_count,solo_unguided_count,notes)
      values (v_logbook.id,v_name,v_attended,v_assisted,v_guided,v_unguided,nullif(btrim(coalesce(v_item->>'notes','')),''));
    end if;
  end loop;

  for v_item in select value from jsonb_array_elements(coalesce(p_conferences,'[]'::jsonb))
  loop
    if nullif(btrim(coalesce(v_item->>'conference_name','')),'') is not null then
      if coalesce(v_item->>'participation','') not in ('attended','speaker') then raise exception 'Conference participation must be attended or speaker'; end if;
      insert into public.prior_experience_conferences(logbook_id,conference_name,participation,conference_date,notes)
      values (
        v_logbook.id,
        btrim(v_item->>'conference_name'),
        v_item->>'participation',
        nullif(v_item->>'conference_date','')::date,
        nullif(btrim(coalesce(v_item->>'notes','')),'')
      );
    end if;
  end loop;

  return v_logbook.id;
end;
$$;
revoke all on function public.save_prior_experience_draft_v1068(uuid,uuid,jsonb,jsonb,text) from public, anon;
grant execute on function public.save_prior_experience_draft_v1068(uuid,uuid,jsonb,jsonb,text) to authenticated;

-- --------------------------------------------------------------
-- Resident: final submission locks editing and starts senior stage.
-- --------------------------------------------------------------
create or replace function public.submit_prior_experience_v1068()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_logbook public.prior_experience_logbooks%rowtype;
  v_year smallint;
  v_owner uuid;
begin
  select p.residency_year into v_year from public.profiles p where p.id=v_uid and p.role::text='resident' and p.is_active=true;
  if v_year is null then raise exception 'Active Resident account required'; end if;

  select * into v_logbook from public.prior_experience_logbooks where resident_id=v_uid for update;
  if not found then raise exception 'Save your Prior Experience Logbook draft first'; end if;
  if v_logbook.status <> 'draft' then raise exception 'This Prior Experience Logbook is already submitted'; end if;
  if v_logbook.senior_1_id is null or v_logbook.senior_2_id is null or v_logbook.senior_1_id=v_logbook.senior_2_id then raise exception 'Choose two different senior residents before final submission'; end if;
  if not exists (select 1 from public.profiles p where p.id=v_logbook.senior_1_id and p.id<>v_uid and p.role::text='resident' and p.is_active=true and (p.residency_year>v_year or (v_year=5 and p.residency_year=5))) then raise exception 'Senior reviewer 1 must be an eligible senior resident'; end if;
  if not exists (select 1 from public.profiles p where p.id=v_logbook.senior_2_id and p.id<>v_uid and p.role::text='resident' and p.is_active=true and (p.residency_year>v_year or (v_year=5 and p.residency_year=5))) then raise exception 'Senior reviewer 2 must be an eligible senior resident'; end if;
  if not exists (select 1 from public.prior_experience_interventions i where i.logbook_id=v_logbook.id)
     and not exists (select 1 from public.prior_experience_conferences c where c.logbook_id=v_logbook.id) then
    raise exception 'Add at least one intervention count or conference before final submission';
  end if;

  delete from public.prior_experience_senior_reviews where logbook_id=v_logbook.id;
  insert into public.prior_experience_senior_reviews(logbook_id, senior_id)
  values (v_logbook.id,v_logbook.senior_1_id),(v_logbook.id,v_logbook.senior_2_id);

  update public.prior_experience_logbooks
     set status='senior_review', submitted_at=now(), updated_at=now()
   where id=v_logbook.id;

  select p.id into v_owner from public.profiles p where p.role::text='owner' and p.is_active=true order by p.created_at nulls last limit 1;

  insert into public.private_messages(sender_id,receiver_id,subject,body)
  select v_uid, sr.senior_id, 'Prior experience senior verification',
         'A resident has finally submitted a Prior Experience Logbook and selected you as one of two senior verifiers. Open Logbook requests to review the full retrospective evidence and approve or reject it.'
  from public.prior_experience_senior_reviews sr where sr.logbook_id=v_logbook.id;

  if v_owner is not null then
    insert into public.private_messages(sender_id,receiver_id,subject,body)
    values (v_uid,v_owner,'Prior Experience Logbook submitted','A resident has submitted a Prior Experience Logbook. Two senior verifications are required before any assessor can act.');
  end if;

  return v_logbook.id;
end;
$$;
revoke all on function public.submit_prior_experience_v1068() from public, anon;
grant execute on function public.submit_prior_experience_v1068() to authenticated;

-- --------------------------------------------------------------
-- Reviewer queue: senior requests first; assessor scopes only after.
-- --------------------------------------------------------------
create or replace function public.get_prior_experience_review_queue_v1068()
returns table(
  review_kind text,
  review_id bigint,
  logbook_id bigint,
  resident_id uuid,
  resident_name text,
  residency_year smallint,
  scope_name text,
  review_status text,
  review_note text,
  submitted_at timestamptz,
  reconsideration_id bigint,
  reconsideration_reason text,
  reconsideration_status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
begin
  select p.role::text into v_role from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role is null then return; end if;

  if v_role='resident' then
    return query
    select 'senior'::text, sr.id, l.id, l.resident_id, rp.display_name, rp.residency_year,
           'Whole prior logbook'::text, sr.status, sr.note, l.submitted_at,
           rec.id, rec.resident_reason, rec.status
    from public.prior_experience_senior_reviews sr
    join public.prior_experience_logbooks l on l.id=sr.logbook_id
    join public.profiles rp on rp.id=l.resident_id
    left join lateral (
      select r.* from public.prior_experience_reconsiderations r
      where r.review_kind='senior' and r.review_id=sr.id
      order by r.created_at desc limit 1
    ) rec on true
    where sr.senior_id=auth.uid()
      and (sr.status='pending' or rec.status='requested')
    order by l.submitted_at;
  elsif v_role='assessor' then
    return query
    select 'assessor'::text, sc.id, l.id, l.resident_id, rp.display_name, rp.residency_year,
           sc.scope_name, sc.status, sc.note, l.submitted_at,
           rec.id, rec.resident_reason, rec.status
    from public.prior_experience_scope_reviews sc
    join public.prior_experience_logbooks l on l.id=sc.logbook_id
    join public.profiles rp on rp.id=l.resident_id
    left join lateral (
      select r.* from public.prior_experience_reconsiderations r
      where r.review_kind='assessor' and r.review_id=sc.id
      order by r.created_at desc limit 1
    ) rec on true
    where (
      (sc.status='pending' and exists (
        select 1 from public.prior_experience_assessor_assignments aa
        where aa.assessor_id=auth.uid() and aa.scope_name=sc.scope_name and aa.is_active=true
      ))
      or (rec.status='requested' and rec.reviewer_id=auth.uid())
    )
    order by l.submitted_at, sc.scope_name;
  end if;
end;
$$;
revoke all on function public.get_prior_experience_review_queue_v1068() from public, anon;
grant execute on function public.get_prior_experience_review_queue_v1068() to authenticated;

-- --------------------------------------------------------------
-- Senior or assessor approves/rejects current stage.
-- --------------------------------------------------------------
create or replace function public.review_prior_experience_v1068(
  p_review_kind text,
  p_review_id bigint,
  p_decision text,
  p_note text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_logbook_id bigint;
  v_resident uuid;
  v_scope text;
  v_status text;
  v_owner uuid;
  v_note text := nullif(btrim(coalesce(p_note,'')),'');
begin
  if p_decision not in ('approved','rejected') then raise exception 'Decision must be approved or rejected'; end if;
  if p_decision='rejected' and v_note is null then raise exception 'A comment is required when rejecting prior experience'; end if;

  if p_review_kind='senior' then
    select sr.logbook_id, l.resident_id into v_logbook_id, v_resident
    from public.prior_experience_senior_reviews sr
    join public.prior_experience_logbooks l on l.id=sr.logbook_id
    where sr.id=p_review_id and sr.senior_id=v_uid and sr.status='pending'
    for update of sr;
    if v_logbook_id is null then raise exception 'Pending senior verification not found'; end if;

    update public.prior_experience_senior_reviews
       set status=p_decision, note=v_note, decided_at=now(), updated_at=now()
     where id=p_review_id;

  elsif p_review_kind='assessor' then
    select sc.logbook_id, l.resident_id, sc.scope_name into v_logbook_id, v_resident, v_scope
    from public.prior_experience_scope_reviews sc
    join public.prior_experience_logbooks l on l.id=sc.logbook_id
    where sc.id=p_review_id and sc.status='pending'
      and exists (
        select 1 from public.prior_experience_assessor_assignments aa
        join public.profiles p on p.id=aa.assessor_id and p.role::text='assessor' and p.is_active=true
        where aa.assessor_id=v_uid and aa.scope_name=sc.scope_name and aa.is_active=true
      )
    for update of sc;
    if v_logbook_id is null then raise exception 'Pending assessor verification not found or this intervention is not assigned to you'; end if;

    update public.prior_experience_scope_reviews
       set status=p_decision, decided_by=v_uid, note=v_note, decided_at=now(), updated_at=now()
     where id=p_review_id;
  else
    raise exception 'Unknown prior-experience review stage';
  end if;

  v_status := public._prior_experience_recalculate_v1068(v_logbook_id);
  select p.id into v_owner from public.profiles p where p.role::text='owner' and p.is_active=true order by p.created_at nulls last limit 1;

  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values (
    v_uid,
    v_resident,
    case when p_decision='approved' then 'Prior experience verification approved' else 'Prior experience verification rejected' end,
    case when p_review_kind='senior' then 'Senior verification' else 'Assessor verification for '||coalesce(v_scope,'prior experience') end ||
    ' was '||p_decision||'.' || case when v_note is not null then E'\nComment: '||v_note else '' end ||
    case when v_status='approved' then E'\nYour Prior Experience Logbook is now fully verified.'
         when p_decision='rejected' then E'\nYou may open Prior Experience Logbook and request reconsideration.'
         when v_status='assessor_review' then E'\nSenior verification is complete and the required assessor scopes are now being reviewed.'
         else '' end
  );

  if v_owner is not null and p_review_kind='assessor' then
    insert into public.private_messages(sender_id,receiver_id,subject,body)
    values (v_uid,v_owner,'Prior experience assessor decision',coalesce(v_scope,'Prior experience')||' was '||p_decision||'.'||case when v_note is not null then E'\nComment: '||v_note else '' end);
  end if;

  return v_status;
end;
$$;
revoke all on function public.review_prior_experience_v1068(text,bigint,text,text) from public, anon;
grant execute on function public.review_prior_experience_v1068(text,bigint,text,text) to authenticated;

-- --------------------------------------------------------------
-- Resident requests reconsideration of a rejected senior/scope.
-- --------------------------------------------------------------
create or replace function public.request_prior_experience_reconsideration_v1068(
  p_review_kind text,
  p_review_id bigint,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_logbook_id bigint;
  v_reviewer uuid;
  v_scope text;
  v_id bigint;
  v_owner uuid;
  v_reason text := nullif(btrim(coalesce(p_reason,'')),'');
begin
  if v_reason is null then raise exception 'Write a reason for reconsideration'; end if;

  if p_review_kind='senior' then
    select sr.logbook_id, sr.senior_id into v_logbook_id, v_reviewer
    from public.prior_experience_senior_reviews sr
    join public.prior_experience_logbooks l on l.id=sr.logbook_id
    where sr.id=p_review_id and l.resident_id=v_uid and sr.status='rejected';
  elsif p_review_kind='assessor' then
    select sc.logbook_id, sc.decided_by, sc.scope_name into v_logbook_id, v_reviewer, v_scope
    from public.prior_experience_scope_reviews sc
    join public.prior_experience_logbooks l on l.id=sc.logbook_id
    where sc.id=p_review_id and l.resident_id=v_uid and sc.status='rejected';
  else
    raise exception 'Unknown prior-experience review stage';
  end if;

  if v_logbook_id is null or v_reviewer is null then raise exception 'Rejected decision not found'; end if;
  if exists (select 1 from public.prior_experience_reconsiderations r where r.review_kind=p_review_kind and r.review_id=p_review_id and r.status='requested') then
    raise exception 'A reconsideration request is already waiting for this reviewer';
  end if;

  insert into public.prior_experience_reconsiderations(logbook_id,review_kind,review_id,reviewer_id,scope_name,resident_reason)
  values (v_logbook_id,p_review_kind,p_review_id,v_reviewer,v_scope,v_reason)
  returning id into v_id;

  select p.id into v_owner from public.profiles p where p.role::text='owner' and p.is_active=true order by p.created_at nulls last limit 1;
  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values (v_uid,v_reviewer,'Prior experience reconsideration requested','A resident requested reconsideration of your rejected '||case when p_review_kind='senior' then 'senior verification' else coalesce(v_scope,'assessor verification') end||E'.\nReason: '||v_reason);
  if v_owner is not null then
    insert into public.private_messages(sender_id,receiver_id,subject,body)
    values (v_uid,v_owner,'Prior experience reconsideration requested','A resident requested reconsideration for '||coalesce(v_scope,'senior verification')||E'.\nReason: '||v_reason);
  end if;
  return v_id;
end;
$$;
revoke all on function public.request_prior_experience_reconsideration_v1068(text,bigint,text) from public, anon;
grant execute on function public.request_prior_experience_reconsideration_v1068(text,bigint,text) to authenticated;

-- --------------------------------------------------------------
-- Exact rejecting reviewer resolves reconsideration.
-- --------------------------------------------------------------
create or replace function public.resolve_prior_experience_reconsideration_v1068(
  p_reconsideration_id bigint,
  p_decision text,
  p_note text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_rec public.prior_experience_reconsiderations%rowtype;
  v_resident uuid;
  v_status text;
  v_note text := nullif(btrim(coalesce(p_note,'')),'');
begin
  if p_decision not in ('approved','rejected') then raise exception 'Decision must be approved or rejected'; end if;
  if p_decision='rejected' and v_note is null then raise exception 'Write a note when keeping the rejection'; end if;

  select * into v_rec from public.prior_experience_reconsiderations r
  where r.id=p_reconsideration_id and r.reviewer_id=v_uid and r.status='requested'
  for update;
  if not found then raise exception 'Pending reconsideration not found'; end if;

  select l.resident_id into v_resident from public.prior_experience_logbooks l where l.id=v_rec.logbook_id;

  if p_decision='approved' then
    if v_rec.review_kind='senior' then
      update public.prior_experience_senior_reviews
         set status='approved', note=concat_ws(E'\n',nullif(note,''),'Reconsideration approved'||case when v_note is not null then ': '||v_note else '' end), decided_at=now(), updated_at=now()
       where id=v_rec.review_id;
    else
      update public.prior_experience_scope_reviews
         set status='approved', note=concat_ws(E'\n',nullif(note,''),'Reconsideration approved'||case when v_note is not null then ': '||v_note else '' end), decided_at=now(), updated_at=now()
       where id=v_rec.review_id;
    end if;
  end if;

  update public.prior_experience_reconsiderations
     set status=p_decision, reviewer_note=v_note, resolved_at=now()
   where id=v_rec.id;

  v_status := public._prior_experience_recalculate_v1068(v_rec.logbook_id);

  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values (v_uid,v_resident,
    case when p_decision='approved' then 'Prior experience reconsideration approved' else 'Prior experience reconsideration rejected' end,
    case when p_decision='approved' then 'Your prior-experience reconsideration was accepted and the original rejection changed to approval.' else 'Your prior-experience reconsideration was not accepted; the original rejection remains.' end ||
    case when v_note is not null then E'\nReviewer note: '||v_note else '' end ||
    case when v_status='approved' then E'\nYour Prior Experience Logbook is now fully verified.' else '' end
  );

  return v_status;
end;
$$;
revoke all on function public.resolve_prior_experience_reconsideration_v1068(bigint,text,text) from public, anon;
grant execute on function public.resolve_prior_experience_reconsideration_v1068(bigint,text,text) to authenticated;

-- --------------------------------------------------------------
-- Owner: read/edit intervention-to-assessor supervision matrix.
-- --------------------------------------------------------------
create or replace function public.get_prior_experience_assessor_assignments_v1068()
returns table(assessor_id uuid, display_name text, scopes text[])
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  return query
  select p.id, p.display_name,
         coalesce(array_agg(a.scope_name order by a.scope_name) filter (where a.is_active=true), array[]::text[])
  from public.profiles p
  left join public.prior_experience_assessor_assignments a on a.assessor_id=p.id and a.is_active=true
  where p.role::text='assessor' and p.is_active=true
  group by p.id,p.display_name
  order by p.display_name;
end;
$$;
revoke all on function public.get_prior_experience_assessor_assignments_v1068() from public, anon;
grant execute on function public.get_prior_experience_assessor_assignments_v1068() to authenticated;

create or replace function public.owner_set_prior_experience_assessor_scopes_v1068(
  p_assessor_id uuid,
  p_scopes text[]
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_scope text;
  v_count integer := 0;
  v_allowed text[] := array[
    'CVP','Intubation','Temporary pacemaker','Permanent pacemaker implantation','Pacemaker programming',
    'ICD implantation','CRT implantation','Pericardiocentesis','TEE','DSE','Coronary angiography',
    'Elective PCI','Primary PCI','IVUS','Rotablation','TAVI','ASD closure','Mitral balloon valvotomy',
    'Exercise stress ECG','Tilting table','Nuclear imaging','CT CA','CMR','CPR','Conferences'
  ];
begin
  if not exists (select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  if not exists (select 1 from public.profiles p where p.id=p_assessor_id and p.role::text='assessor' and p.is_active=true) then raise exception 'Active assessor not found'; end if;

  update public.prior_experience_assessor_assignments
     set is_active=false, updated_at=now(), assigned_by=auth.uid()
   where assessor_id=p_assessor_id and is_active=true;

  foreach v_scope in array coalesce(p_scopes,array[]::text[])
  loop
    if not (v_scope = any(v_allowed)) then raise exception 'Unsupported assessor scope: %', v_scope; end if;
    insert into public.prior_experience_assessor_assignments(assessor_id,scope_name,is_active,assigned_by,updated_at)
    values (p_assessor_id,v_scope,true,auth.uid(),now())
    on conflict (assessor_id,scope_name) do update set is_active=true, assigned_by=excluded.assigned_by, updated_at=now();
    v_count := v_count + 1;

    -- If there are already waiting scope reviews, notify this newly assigned assessor.
    insert into public.private_messages(sender_id,receiver_id,subject,body)
    select auth.uid(), p_assessor_id, 'Prior experience verification waiting',
           'A Prior Experience Logbook is already waiting for verification in your newly assigned scope: '||v_scope||'. Open Logbook requests.'
    from public.prior_experience_scope_reviews sc
    join public.prior_experience_logbooks l on l.id=sc.logbook_id
    where sc.scope_name=v_scope and sc.status='pending' and l.status in ('assessor_review','rejected')
      and not exists (
        select 1 from public.private_messages pm
        where pm.receiver_id=p_assessor_id and pm.subject='Prior experience verification waiting'
          and pm.body like '%'||v_scope||'%'
          and pm.created_at > now()-interval '1 day'
      )
    limit 1;
  end loop;
  return v_count;
end;
$$;
revoke all on function public.owner_set_prior_experience_assessor_scopes_v1068(uuid,text[]) from public, anon;
grant execute on function public.owner_set_prior_experience_assessor_scopes_v1068(uuid,text[]) to authenticated;

commit;
