-- Resident Training & Assessment v1.0.69
-- Prior Experience owner control + exactly two intervention assessors + 48h pending-request reminders.
-- Incremental migration after v1.0.68.

begin;

-- =============================================================================
-- 1) PRIOR EXPERIENCE: exactly two named assessors per scope.
-- =============================================================================
create table if not exists public.prior_experience_scope_assessor_pairs (
  scope_name text primary key,
  junior_assessor_id uuid not null references public.profiles(id),
  senior_assessor_id uuid not null references public.profiles(id),
  assigned_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  constraint prior_experience_pair_distinct_check check (junior_assessor_id <> senior_assessor_id)
);

create table if not exists public.prior_experience_scope_verifications (
  id bigint generated by default as identity primary key,
  logbook_id bigint not null references public.prior_experience_logbooks(id) on delete cascade,
  scope_name text not null,
  assessor_level text not null,
  assessor_id uuid not null references public.profiles(id),
  status text not null default 'pending',
  note text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(logbook_id, scope_name, assessor_level),
  constraint prior_experience_scope_verification_level_check check (assessor_level in ('junior','senior')),
  constraint prior_experience_scope_verification_status_check check (status in ('pending','approved','rejected'))
);

create index if not exists prior_experience_scope_verifications_queue_idx
  on public.prior_experience_scope_verifications(assessor_id,status,created_at);

alter table public.prior_experience_scope_assessor_pairs enable row level security;
alter table public.prior_experience_scope_verifications enable row level security;
revoke all on public.prior_experience_scope_assessor_pairs from public, anon, authenticated;
revoke all on public.prior_experience_scope_verifications from public, anon, authenticated;

-- Reconsiderations now point either to one senior signature or one exact assessor signature.
alter table public.prior_experience_reconsiderations
  drop constraint if exists prior_experience_reconsideration_kind_check;
alter table public.prior_experience_reconsiderations
  add constraint prior_experience_reconsideration_kind_check
  check (review_kind in ('senior','assessor','scope_verification'));

-- Link Prior Experience request messages to their exact pending decision. Used
-- by the 48-hour reminder system so the reminder updates the same request/thread.
create table if not exists public.prior_experience_request_message_links_v1069 (
  message_id bigint primary key references public.private_messages(id) on delete cascade,
  request_kind text not null,
  review_id bigint not null,
  created_at timestamptz not null default now(),
  unique(request_kind,review_id)
);
alter table public.prior_experience_request_message_links_v1069 enable row level security;
revoke all on public.prior_experience_request_message_links_v1069 from public, anon, authenticated;

-- Automatically link future senior-verification messages created by the existing
-- v1.0.68 submit RPC to the exact pending senior signature.
create or replace function public._link_prior_senior_message_v1069()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v_review_id bigint;
begin
  if new.subject='Prior experience senior verification' then
    select sr.id into v_review_id
    from public.prior_experience_senior_reviews sr
    where sr.senior_id=new.receiver_id and sr.status='pending'
      and sr.created_at between new.created_at-interval '10 minutes' and new.created_at+interval '2 minutes'
    order by abs(extract(epoch from (sr.created_at-new.created_at)))
    limit 1;
    if v_review_id is not null then
      insert into public.prior_experience_request_message_links_v1069(message_id,request_kind,review_id)
      values(new.id,'senior',v_review_id)
      on conflict(request_kind,review_id) do nothing;
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists link_prior_senior_message_v1069 on public.private_messages;
create trigger link_prior_senior_message_v1069 after insert on public.private_messages
for each row execute function public._link_prior_senior_message_v1069();

-- Backfill existing senior request messages where possible.
insert into public.prior_experience_request_message_links_v1069(message_id,request_kind,review_id)
select distinct on (sr.id) pm.id, 'senior', sr.id
from public.prior_experience_senior_reviews sr
join public.prior_experience_logbooks l on l.id=sr.logbook_id
join public.private_messages pm
  on pm.receiver_id=sr.senior_id
 and pm.subject='Prior experience senior verification'
 and pm.created_at between sr.created_at - interval '2 minutes' and sr.created_at + interval '10 minutes'
order by sr.id, abs(extract(epoch from (pm.created_at-sr.created_at)))
on conflict (request_kind,review_id) do nothing;

-- Helper: the scopes actually present in one Prior Experience submission.
create or replace function public._prior_experience_scope_names_v1069(p_logbook_id bigint)
returns table(scope_name text)
language sql
stable
security definer
set search_path=public
as $$
  select distinct i.intervention_name
  from public.prior_experience_interventions i
  where i.logbook_id=p_logbook_id
    and (i.attended_count+i.assisted_count+i.solo_guided_count+i.solo_unguided_count)>0
  union
  select 'Conferences'
  where exists(select 1 from public.prior_experience_conferences c where c.logbook_id=p_logbook_id);
$$;
revoke all on function public._prior_experience_scope_names_v1069(bigint) from public,anon,authenticated;

-- Create/update the two pending signatures for every scope. Completed signatures
-- are never reassigned when Owner later edits the supervision matrix.
create or replace function public._prior_experience_sync_verifications_v1069(p_logbook_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_scope text;
  v_pair public.prior_experience_scope_assessor_pairs%rowtype;
  v_verification_id bigint;
  v_resident uuid;
  v_resident_name text;
  v_owner uuid;
  v_message_id bigint;
begin
  select l.resident_id,rp.display_name into v_resident,v_resident_name
  from public.prior_experience_logbooks l join public.profiles rp on rp.id=l.resident_id
  where l.id=p_logbook_id;
  if v_resident is null then return; end if;

  select p.id into v_owner from public.profiles p
  where p.role::text='owner' and p.is_active=true order by p.created_at nulls last limit 1;

  for v_scope in select s.scope_name from public._prior_experience_scope_names_v1069(p_logbook_id) s
  loop
    select * into v_pair from public.prior_experience_scope_assessor_pairs p where p.scope_name=v_scope;
    if not found then continue; end if;

    -- Junior signature.
    insert into public.prior_experience_scope_verifications(logbook_id,scope_name,assessor_level,assessor_id)
    values(p_logbook_id,v_scope,'junior',v_pair.junior_assessor_id)
    on conflict(logbook_id,scope_name,assessor_level) do update
      set assessor_id=case when prior_experience_scope_verifications.status='pending' then excluded.assessor_id else prior_experience_scope_verifications.assessor_id end,
          updated_at=now()
    returning id into v_verification_id;

    if exists(select 1 from public.prior_experience_scope_verifications v where v.id=v_verification_id and v.status='pending')
       and not exists(select 1 from public.prior_experience_request_message_links_v1069 l where l.request_kind='scope_verification' and l.review_id=v_verification_id) then
      insert into public.private_messages(sender_id,receiver_id,subject,body)
      values(coalesce(v_owner,v_resident),v_pair.junior_assessor_id,'Prior experience verification request',
             'Prior Experience verification · '||v_scope||E'\nResident: '||coalesce(v_resident_name,'Resident')||E'\nRole: Junior assessor signature\nBoth the junior and senior assessor signatures are required.')
      returning id into v_message_id;
      insert into public.prior_experience_request_message_links_v1069(message_id,request_kind,review_id)
      values(v_message_id,'scope_verification',v_verification_id)
      on conflict(request_kind,review_id) do nothing;
    end if;

    -- Senior/older signature.
    insert into public.prior_experience_scope_verifications(logbook_id,scope_name,assessor_level,assessor_id)
    values(p_logbook_id,v_scope,'senior',v_pair.senior_assessor_id)
    on conflict(logbook_id,scope_name,assessor_level) do update
      set assessor_id=case when prior_experience_scope_verifications.status='pending' then excluded.assessor_id else prior_experience_scope_verifications.assessor_id end,
          updated_at=now()
    returning id into v_verification_id;

    if exists(select 1 from public.prior_experience_scope_verifications v where v.id=v_verification_id and v.status='pending')
       and not exists(select 1 from public.prior_experience_request_message_links_v1069 l where l.request_kind='scope_verification' and l.review_id=v_verification_id) then
      insert into public.private_messages(sender_id,receiver_id,subject,body)
      values(coalesce(v_owner,v_resident),v_pair.senior_assessor_id,'Prior experience verification request',
             'Prior Experience verification · '||v_scope||E'\nResident: '||coalesce(v_resident_name,'Resident')||E'\nRole: Senior assessor signature\nBoth the junior and senior assessor signatures are required.')
      returning id into v_message_id;
      insert into public.prior_experience_request_message_links_v1069(message_id,request_kind,review_id)
      values(v_message_id,'scope_verification',v_verification_id)
      on conflict(request_kind,review_id) do nothing;
    end if;
  end loop;
end;
$$;
revoke all on function public._prior_experience_sync_verifications_v1069(bigint) from public,anon,authenticated;

create or replace function public._prior_experience_recalculate_v1069(p_logbook_id bigint)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  v_senior_total int;
  v_senior_approved int;
  v_senior_rejected int;
  v_scope_total int;
  v_ver_total int;
  v_ver_approved int;
  v_ver_rejected int;
  v_status text;
begin
  select count(*),count(*) filter(where status='approved'),count(*) filter(where status='rejected')
  into v_senior_total,v_senior_approved,v_senior_rejected
  from public.prior_experience_senior_reviews where logbook_id=p_logbook_id;

  if v_senior_rejected>0 then
    v_status:='rejected';
  elsif v_senior_total<2 or v_senior_approved<2 then
    v_status:='senior_review';
  else
    perform public._prior_experience_sync_verifications_v1069(p_logbook_id);
    select count(*) into v_scope_total from public._prior_experience_scope_names_v1069(p_logbook_id);
    select count(*),count(*) filter(where status='approved'),count(*) filter(where status='rejected')
      into v_ver_total,v_ver_approved,v_ver_rejected
    from public.prior_experience_scope_verifications v
    where v.logbook_id=p_logbook_id
      and exists(select 1 from public._prior_experience_scope_names_v1069(p_logbook_id) s where s.scope_name=v.scope_name);

    if v_ver_rejected>0 then v_status:='rejected';
    elsif v_scope_total=0 or v_ver_total < v_scope_total*2 or v_ver_approved < v_scope_total*2 then v_status:='assessor_review';
    else v_status:='approved'; end if;
  end if;

  update public.prior_experience_logbooks
  set status=v_status,
      verified_at=case when v_status='approved' then coalesce(verified_at,now()) else null end,
      updated_at=now()
  where id=p_logbook_id;
  return v_status;
end;
$$;
revoke all on function public._prior_experience_recalculate_v1069(bigint) from public,anon,authenticated;

-- Existing senior-review RPC calls v1068 helper. Delegate it to the new two-assessor engine.
create or replace function public._prior_experience_recalculate_v1068(p_logbook_id bigint)
returns text
language plpgsql
security definer
set search_path=public
as $$ begin return public._prior_experience_recalculate_v1069(p_logbook_id); end; $$;
revoke all on function public._prior_experience_recalculate_v1068(bigint) from public,anon,authenticated;

-- New read model used by resident, assessor and Owner screens.
create or replace function public.get_prior_experience_submission_v1069(p_logbook_id bigint default null)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid(); v_role text; v_logbook_id bigint; v_header jsonb;
begin
  select p.role::text into v_role from public.profiles p where p.id=v_uid and p.is_active=true;
  if v_role is null then raise exception 'Active account required'; end if;
  if p_logbook_id is null then
    if v_role<>'resident' then return null; end if;
    select l.id into v_logbook_id from public.prior_experience_logbooks l where l.resident_id=v_uid;
    if v_logbook_id is null then return null; end if;
  else v_logbook_id:=p_logbook_id; end if;

  if not exists(
    select 1 from public.prior_experience_logbooks l where l.id=v_logbook_id and (
      v_role='owner' or l.resident_id=v_uid or l.senior_1_id=v_uid or l.senior_2_id=v_uid
      or exists(select 1 from public.prior_experience_scope_verifications v where v.logbook_id=l.id and v.assessor_id=v_uid)
      or exists(select 1 from public.prior_experience_reconsiderations r where r.logbook_id=l.id and r.reviewer_id=v_uid)
    )
  ) then raise exception 'You cannot view this Prior Experience Logbook'; end if;

  select jsonb_build_object('id',l.id,'resident_id',l.resident_id,'resident_name',rp.display_name,
    'residency_year',rp.residency_year,'status',l.status,'senior_1_id',l.senior_1_id,'senior_2_id',l.senior_2_id,
    'senior_1_name',s1.display_name,'senior_2_name',s2.display_name,'resident_notes',l.resident_notes,
    'submitted_at',l.submitted_at,'verified_at',l.verified_at,'updated_at',l.updated_at,
    'editable',(l.resident_id=v_uid and l.status='draft'))
  into v_header
  from public.prior_experience_logbooks l join public.profiles rp on rp.id=l.resident_id
  left join public.profiles s1 on s1.id=l.senior_1_id left join public.profiles s2 on s2.id=l.senior_2_id
  where l.id=v_logbook_id;

  return jsonb_build_object(
    'header',v_header,
    'interventions',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'intervention_name',i.intervention_name,
      'attended_count',i.attended_count,'assisted_count',i.assisted_count,'solo_guided_count',i.solo_guided_count,
      'solo_unguided_count',i.solo_unguided_count,'notes',i.notes) order by i.id)
      from public.prior_experience_interventions i where i.logbook_id=v_logbook_id),'[]'::jsonb),
    'conferences',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'conference_name',c.conference_name,
      'participation',c.participation,'conference_date',c.conference_date,'notes',c.notes) order by c.id)
      from public.prior_experience_conferences c where c.logbook_id=v_logbook_id),'[]'::jsonb),
    'senior_reviews',coalesce((select jsonb_agg(jsonb_build_object('id',sr.id,'senior_id',sr.senior_id,'senior_name',p.display_name,
      'status',sr.status,'note',sr.note,'decided_at',sr.decided_at) order by sr.id)
      from public.prior_experience_senior_reviews sr join public.profiles p on p.id=sr.senior_id where sr.logbook_id=v_logbook_id),'[]'::jsonb),
    'scope_verifications',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'scope_name',v.scope_name,
      'assessor_level',v.assessor_level,'assessor_id',v.assessor_id,'assessor_name',p.display_name,'status',v.status,
      'note',v.note,'decided_at',v.decided_at) order by v.scope_name,v.assessor_level)
      from public.prior_experience_scope_verifications v join public.profiles p on p.id=v.assessor_id where v.logbook_id=v_logbook_id),'[]'::jsonb),
    'reconsiderations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'review_kind',r.review_kind,'review_id',r.review_id,
      'reviewer_id',r.reviewer_id,'reviewer_name',p.display_name,'scope_name',r.scope_name,'resident_reason',r.resident_reason,
      'status',r.status,'reviewer_note',r.reviewer_note,'created_at',r.created_at,'resolved_at',r.resolved_at) order by r.created_at)
      from public.prior_experience_reconsiderations r join public.profiles p on p.id=r.reviewer_id where r.logbook_id=v_logbook_id),'[]'::jsonb)
  );
end;
$$;
revoke all on function public.get_prior_experience_submission_v1069(bigint) from public,anon;
grant execute on function public.get_prior_experience_submission_v1069(bigint) to authenticated;

create or replace function public.get_prior_experience_review_queue_v1069()
returns table(
  review_kind text,review_id bigint,logbook_id bigint,resident_id uuid,resident_name text,residency_year smallint,
  scope_name text,assessor_level text,review_status text,review_note text,submitted_at timestamptz,
  reconsideration_id bigint,reconsideration_status text,reconsideration_reason text
)
language plpgsql
security definer
set search_path=public
as $$
declare v_role text;
begin
  select p.role::text into v_role from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role is null then raise exception 'Active account required'; end if;

  if v_role='resident' then
    return query
    select 'senior'::text,sr.id,l.id,l.resident_id,rp.display_name,rp.residency_year,'Whole prior logbook'::text,null::text,
      sr.status,sr.note,l.submitted_at,rec.id,rec.status,rec.resident_reason
    from public.prior_experience_senior_reviews sr
    join public.prior_experience_logbooks l on l.id=sr.logbook_id join public.profiles rp on rp.id=l.resident_id
    left join lateral(select r.* from public.prior_experience_reconsiderations r where r.review_kind='senior' and r.review_id=sr.id order by r.created_at desc limit 1) rec on true
    where sr.senior_id=auth.uid() and (sr.status='pending' or rec.status='requested')
    order by l.submitted_at;
  elsif v_role='assessor' then
    return query
    select 'scope_verification'::text,v.id,l.id,l.resident_id,rp.display_name,rp.residency_year,v.scope_name,v.assessor_level,
      v.status,v.note,l.submitted_at,rec.id,rec.status,rec.resident_reason
    from public.prior_experience_scope_verifications v
    join public.prior_experience_logbooks l on l.id=v.logbook_id join public.profiles rp on rp.id=l.resident_id
    left join lateral(select r.* from public.prior_experience_reconsiderations r where r.review_kind='scope_verification' and r.review_id=v.id order by r.created_at desc limit 1) rec on true
    where v.assessor_id=auth.uid() and (v.status='pending' or rec.status='requested')
    order by l.submitted_at,v.scope_name,v.assessor_level;
  else return; end if;
end;
$$;
revoke all on function public.get_prior_experience_review_queue_v1069() from public,anon;
grant execute on function public.get_prior_experience_review_queue_v1069() to authenticated;

create or replace function public.review_prior_experience_v1069(p_review_kind text,p_review_id bigint,p_decision text,p_note text default null)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid(); v_logbook_id bigint; v_resident uuid; v_scope text; v_level text; v_status text;
  v_name text; v_note text:=nullif(btrim(coalesce(p_note,'')),'');
begin
  if p_decision not in ('approved','rejected') then raise exception 'Decision must be approved or rejected'; end if;
  if p_decision='rejected' and v_note is null then raise exception 'Write a comment before rejecting'; end if;
  select p.display_name into v_name from public.profiles p where p.id=v_uid and p.is_active=true;
  if v_name is null then raise exception 'Active reviewer required'; end if;

  if p_review_kind='senior' then
    select sr.logbook_id,l.resident_id into v_logbook_id,v_resident
    from public.prior_experience_senior_reviews sr join public.prior_experience_logbooks l on l.id=sr.logbook_id
    where sr.id=p_review_id and sr.senior_id=v_uid and sr.status='pending' for update of sr;
    if v_logbook_id is null then raise exception 'Pending senior verification not found'; end if;
    update public.prior_experience_senior_reviews set status=p_decision,note=v_note,decided_at=now(),updated_at=now() where id=p_review_id;
  elsif p_review_kind='scope_verification' then
    select v.logbook_id,l.resident_id,v.scope_name,v.assessor_level into v_logbook_id,v_resident,v_scope,v_level
    from public.prior_experience_scope_verifications v join public.prior_experience_logbooks l on l.id=v.logbook_id
    where v.id=p_review_id and v.assessor_id=v_uid and v.status='pending' for update of v;
    if v_logbook_id is null then raise exception 'Pending assessor signature not found'; end if;
    update public.prior_experience_scope_verifications
    set status=p_decision,note=v_note,decided_at=now(),updated_at=now() where id=p_review_id;
  else raise exception 'Unknown Prior Experience review stage'; end if;

  v_status:=public._prior_experience_recalculate_v1069(v_logbook_id);
  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values(v_uid,v_resident,
    case when p_decision='approved' then 'Prior experience approval' else 'Prior experience rejection' end,
    v_name||' '||p_decision||' your '||case when p_review_kind='senior' then 'senior-verification stage' else coalesce(v_scope,'Prior Experience scope')||' ('||initcap(v_level)||' assessor signature)' end||'.'||
    case when v_note is not null then E'\nComment: '||v_note else '' end||
    case when v_status='approved' then E'\n✓ Your Prior Experience Logbook is now fully verified.' when p_decision='rejected' then E'\nYou may request reconsideration.' else '' end);
  return v_status;
end;
$$;
revoke all on function public.review_prior_experience_v1069(text,bigint,text,text) from public,anon;
grant execute on function public.review_prior_experience_v1069(text,bigint,text,text) to authenticated;

create or replace function public.request_prior_experience_reconsideration_v1069(p_review_kind text,p_review_id bigint,p_reason text)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid(); v_logbook_id bigint; v_reviewer uuid; v_scope text; v_id bigint; v_owner uuid; v_message bigint;
  v_reason text:=nullif(btrim(coalesce(p_reason,'')),'');
begin
  if v_reason is null then raise exception 'Write a reason for reconsideration'; end if;
  if p_review_kind='senior' then
    select sr.logbook_id,sr.senior_id into v_logbook_id,v_reviewer
    from public.prior_experience_senior_reviews sr join public.prior_experience_logbooks l on l.id=sr.logbook_id
    where sr.id=p_review_id and l.resident_id=v_uid and sr.status='rejected';
  elsif p_review_kind='scope_verification' then
    select v.logbook_id,v.assessor_id,v.scope_name into v_logbook_id,v_reviewer,v_scope
    from public.prior_experience_scope_verifications v join public.prior_experience_logbooks l on l.id=v.logbook_id
    where v.id=p_review_id and l.resident_id=v_uid and v.status='rejected';
  else raise exception 'Unknown Prior Experience review stage'; end if;
  if v_logbook_id is null then raise exception 'Rejected decision not found'; end if;
  if exists(select 1 from public.prior_experience_reconsiderations r where r.review_kind=p_review_kind and r.review_id=p_review_id and r.status='requested') then
    raise exception 'A reconsideration request is already waiting for this reviewer';
  end if;
  insert into public.prior_experience_reconsiderations(logbook_id,review_kind,review_id,reviewer_id,scope_name,resident_reason)
  values(v_logbook_id,p_review_kind,p_review_id,v_reviewer,v_scope,v_reason) returning id into v_id;

  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values(v_uid,v_reviewer,'Prior experience reconsideration requested',
    'Prior Experience reconsideration'||case when v_scope is not null then ' · '||v_scope else '' end||E'\nReason: '||v_reason)
  returning id into v_message;
  insert into public.prior_experience_request_message_links_v1069(message_id,request_kind,review_id)
  values(v_message,'reconsideration',v_id) on conflict(request_kind,review_id) do nothing;

  select p.id into v_owner from public.profiles p where p.role::text='owner' and p.is_active=true order by p.created_at nulls last limit 1;
  if v_owner is not null then
    insert into public.private_messages(sender_id,receiver_id,subject,body)
    values(v_uid,v_owner,'Prior experience reconsideration requested','A Prior Experience reconsideration is awaiting '||coalesce((select display_name from public.profiles where id=v_reviewer),'reviewer')||'.');
  end if;
  return v_id;
end;
$$;
revoke all on function public.request_prior_experience_reconsideration_v1069(text,bigint,text) from public,anon;
grant execute on function public.request_prior_experience_reconsideration_v1069(text,bigint,text) to authenticated;

create or replace function public.resolve_prior_experience_reconsideration_v1069(p_reconsideration_id bigint,p_decision text,p_note text default null)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid(); v_rec public.prior_experience_reconsiderations%rowtype; v_resident uuid; v_status text;
  v_note text:=nullif(btrim(coalesce(p_note,'')),'');
begin
  if p_decision not in ('approved','rejected') then raise exception 'Decision must be approved or rejected'; end if;
  if p_decision='rejected' and v_note is null then raise exception 'Write a note when keeping the rejection'; end if;
  select * into v_rec from public.prior_experience_reconsiderations r
  where r.id=p_reconsideration_id and r.reviewer_id=v_uid and r.status='requested' for update;
  if not found then raise exception 'Pending reconsideration not found'; end if;
  select l.resident_id into v_resident from public.prior_experience_logbooks l where l.id=v_rec.logbook_id;
  if p_decision='approved' then
    if v_rec.review_kind='senior' then
      update public.prior_experience_senior_reviews set status='approved',note=concat_ws(E'\n',nullif(note,''),'Reconsideration approved'||case when v_note is not null then ': '||v_note else '' end),decided_at=now(),updated_at=now() where id=v_rec.review_id;
    elsif v_rec.review_kind='scope_verification' then
      update public.prior_experience_scope_verifications set status='approved',note=concat_ws(E'\n',nullif(note,''),'Reconsideration approved'||case when v_note is not null then ': '||v_note else '' end),decided_at=now(),updated_at=now() where id=v_rec.review_id;
    end if;
  end if;
  update public.prior_experience_reconsiderations set status=p_decision,reviewer_note=v_note,resolved_at=now() where id=v_rec.id;
  v_status:=public._prior_experience_recalculate_v1069(v_rec.logbook_id);
  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values(v_uid,v_resident,case when p_decision='approved' then 'Prior experience reconsideration approved' else 'Prior experience reconsideration rejected' end,
    case when p_decision='approved' then 'Your reconsideration was accepted and the original rejection changed to approval.' else 'Your reconsideration was not accepted; the original rejection remains.' end||
    case when v_note is not null then E'\nReviewer note: '||v_note else '' end||case when v_status='approved' then E'\n✓ Your Prior Experience Logbook is fully verified.' else '' end);
  return v_status;
end;
$$;
revoke all on function public.resolve_prior_experience_reconsideration_v1069(bigint,text,text) from public,anon;
grant execute on function public.resolve_prior_experience_reconsideration_v1069(bigint,text,text) to authenticated;

-- Owner matrix: one junior + one senior/older assessor for every manual scope.
create or replace function public.owner_get_prior_experience_assessor_pairs_v1069()
returns table(scope_name text,junior_assessor_id uuid,junior_assessor_name text,senior_assessor_id uuid,senior_assessor_name text)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  return query
  with scopes(scope_name,ord) as (values
    ('CVP',1),('Intubation',2),('Temporary pacemaker',3),('Permanent pacemaker implantation',4),('Pacemaker programming',5),
    ('ICD implantation',6),('CRT implantation',7),('Pericardiocentesis',8),('TEE',9),('DSE',10),('Coronary angiography',11),
    ('Elective PCI',12),('Primary PCI',13),('IVUS',14),('Rotablation',15),('TAVI',16),('ASD closure',17),('Mitral balloon valvotomy',18),
    ('Exercise stress ECG',19),('Tilting table',20),('Nuclear imaging',21),('CT CA',22),('CMR',23),('CPR',24),('Conferences',25)
  )
  select s.scope_name,pair.junior_assessor_id,j.display_name,pair.senior_assessor_id,sp.display_name
  from scopes s left join public.prior_experience_scope_assessor_pairs pair on pair.scope_name=s.scope_name
  left join public.profiles j on j.id=pair.junior_assessor_id left join public.profiles sp on sp.id=pair.senior_assessor_id
  order by s.ord;
end;
$$;
revoke all on function public.owner_get_prior_experience_assessor_pairs_v1069() from public,anon;
grant execute on function public.owner_get_prior_experience_assessor_pairs_v1069() to authenticated;

create or replace function public.owner_set_prior_experience_assessor_pair_v1069(p_scope_name text,p_junior_assessor_id uuid,p_senior_assessor_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_logbook_id bigint;
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  if p_junior_assessor_id=p_senior_assessor_id then raise exception 'Choose two different assessors'; end if;
  if not exists(select 1 from public.profiles p where p.id=p_junior_assessor_id and p.role::text='assessor' and p.is_active=true) then raise exception 'Choose an active junior assessor'; end if;
  if not exists(select 1 from public.profiles p where p.id=p_senior_assessor_id and p.role::text='assessor' and p.is_active=true) then raise exception 'Choose an active senior assessor'; end if;
  if p_scope_name not in ('CVP','Intubation','Temporary pacemaker','Permanent pacemaker implantation','Pacemaker programming','ICD implantation','CRT implantation','Pericardiocentesis','TEE','DSE','Coronary angiography','Elective PCI','Primary PCI','IVUS','Rotablation','TAVI','ASD closure','Mitral balloon valvotomy','Exercise stress ECG','Tilting table','Nuclear imaging','CT CA','CMR','CPR','Conferences') then raise exception 'Unsupported scope'; end if;

  insert into public.prior_experience_scope_assessor_pairs(scope_name,junior_assessor_id,senior_assessor_id,assigned_by,updated_at)
  values(p_scope_name,p_junior_assessor_id,p_senior_assessor_id,auth.uid(),now())
  on conflict(scope_name) do update set junior_assessor_id=excluded.junior_assessor_id,senior_assessor_id=excluded.senior_assessor_id,assigned_by=excluded.assigned_by,updated_at=now();

  for v_logbook_id in
    select l.id from public.prior_experience_logbooks l
    where l.status in ('assessor_review','rejected') and exists(select 1 from public._prior_experience_scope_names_v1069(l.id) s where s.scope_name=p_scope_name)
  loop
    -- Pending signatures follow the newly edited pair. Completed signatures stay historical.
    delete from public.private_messages pm
    using public.prior_experience_request_message_links_v1069 ml, public.prior_experience_scope_verifications v
    where ml.message_id=pm.id and ml.request_kind='scope_verification' and ml.review_id=v.id
      and v.logbook_id=v_logbook_id and v.scope_name=p_scope_name and v.status='pending'
      and ((v.assessor_level='junior' and v.assessor_id<>p_junior_assessor_id) or (v.assessor_level='senior' and v.assessor_id<>p_senior_assessor_id));
    update public.prior_experience_scope_verifications v
      set assessor_id=case when v.assessor_level='junior' then p_junior_assessor_id else p_senior_assessor_id end,updated_at=now()
      where v.logbook_id=v_logbook_id and v.scope_name=p_scope_name and v.status='pending';
    perform public._prior_experience_sync_verifications_v1069(v_logbook_id);
    perform public._prior_experience_recalculate_v1069(v_logbook_id);
  end loop;
end;
$$;
revoke all on function public.owner_set_prior_experience_assessor_pair_v1069(text,uuid,uuid) from public,anon;
grant execute on function public.owner_set_prior_experience_assessor_pair_v1069(text,uuid,uuid) to authenticated;

-- =============================================================================
-- 2) OWNER: all Prior Experience statuses, review and reset.
-- =============================================================================
create or replace function public.owner_prior_experience_status_v1069()
returns table(
  resident_id uuid,resident_name text,residency_year smallint,logbook_id bigint,status text,submitted_at timestamptz,verified_at timestamptz,updated_at timestamptz,
  senior_approved integer,senior_pending integer,senior_rejected integer,assessor_approved integer,assessor_pending integer,assessor_rejected integer
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  return query
  select p.id,p.display_name,p.residency_year,l.id,coalesce(l.status,'not_started'),l.submitted_at,l.verified_at,l.updated_at,
    coalesce((select count(*)::int from public.prior_experience_senior_reviews sr where sr.logbook_id=l.id and sr.status='approved'),0),
    coalesce((select count(*)::int from public.prior_experience_senior_reviews sr where sr.logbook_id=l.id and sr.status='pending'),0),
    coalesce((select count(*)::int from public.prior_experience_senior_reviews sr where sr.logbook_id=l.id and sr.status='rejected'),0),
    coalesce((select count(*)::int from public.prior_experience_scope_verifications v where v.logbook_id=l.id and v.status='approved'),0),
    coalesce((select count(*)::int from public.prior_experience_scope_verifications v where v.logbook_id=l.id and v.status='pending'),0),
    coalesce((select count(*)::int from public.prior_experience_scope_verifications v where v.logbook_id=l.id and v.status='rejected'),0)
  from public.profiles p left join public.prior_experience_logbooks l on l.resident_id=p.id
  where p.role::text='resident' and p.is_active=true
  order by p.residency_year,p.display_name;
end;
$$;
revoke all on function public.owner_prior_experience_status_v1069() from public,anon;
grant execute on function public.owner_prior_experience_status_v1069() to authenticated;

create or replace function public.owner_reset_all_prior_experience_v1069()
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare v_count integer;
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  select count(*)::int into v_count from public.prior_experience_logbooks;
  delete from public.private_messages where lower(coalesce(subject,'')) like 'prior experience%';
  delete from public.prior_experience_logbooks where id is not null;
  delete from public.workflow_request_reminder_state_v1069 where request_key like 'prior-%';
  return v_count;
exception when undefined_table then
  -- workflow reminder table may not yet exist during first migration pass.
  delete from public.prior_experience_logbooks where id is not null;
  return v_count;
end;
$$;

-- =============================================================================
-- 3) GENERIC PENDING REQUEST MONITOR + 48-HOUR REMINDER.
-- =============================================================================
create table if not exists public.workflow_request_reminder_state_v1069 (
  request_key text primary key,
  original_message_id bigint references public.private_messages(id) on delete set null,
  reminded_at timestamptz,
  last_pending_seen_at timestamptz not null default now()
);
alter table public.workflow_request_reminder_state_v1069 enable row level security;
revoke all on public.workflow_request_reminder_state_v1069 from public,anon,authenticated;

-- Recreate reset now that reminder table is guaranteed to exist.
create or replace function public.owner_reset_all_prior_experience_v1069()
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare v_count integer;
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  select count(*)::int into v_count from public.prior_experience_logbooks;
  delete from public.private_messages where lower(coalesce(subject,'')) like 'prior experience%';
  delete from public.prior_experience_logbooks where id is not null;
  delete from public.workflow_request_reminder_state_v1069 where request_key like 'prior-%';
  return v_count;
end;
$$;
revoke all on function public.owner_reset_all_prior_experience_v1069() from public,anon;
grant execute on function public.owner_reset_all_prior_experience_v1069() to authenticated;

-- Internal live list of all unanswered requests directed to a senior or assessor.
create or replace function public._pending_request_rows_v1069()
returns table(
  request_key text,request_type text,sender_id uuid,sender_name text,topic text,reviewer_id uuid,reviewer_name text,reviewer_role text,issued_at timestamptz,original_message_id bigint
)
language sql
stable
security definer
set search_path=public
as $$
  -- Current e-logbook: senior stage.
  select 'logbook:'||le.id::text||':senior','Current logbook · senior approval',le.resident_id,rp.display_name,
    coalesce(le.procedure_name,le.title,'Logbook activity'),le.senior_resident_id,sp.display_name,'Senior resident',coalesce(le.created_at,le.activity_date::timestamptz),
    (select pm.id from public.private_messages pm where pm.logbook_entry_id=le.id and pm.receiver_id=le.senior_resident_id and pm.subject like 'Logbook approval request%' order by pm.created_at desc limit 1)
  from public.resident_logbook_entries le join public.profiles rp on rp.id=le.resident_id join public.profiles sp on sp.id=le.senior_resident_id
  where le.activity_category='manual_intervention' and le.senior_status='pending'

  union all
  -- Current e-logbook: assessor stage after senior approval.
  select 'logbook:'||le.id::text||':assessor','Current logbook · assessor approval',le.resident_id,rp.display_name,
    coalesce(le.procedure_name,le.title,'Logbook activity'),le.assessor_id,ap.display_name,'Assessor',coalesce(le.senior_reviewed_at,le.created_at,le.activity_date::timestamptz),
    (select pm.id from public.private_messages pm where pm.logbook_entry_id=le.id and pm.receiver_id=le.assessor_id and pm.subject like 'Logbook approval request%' order by pm.created_at desc limit 1)
  from public.resident_logbook_entries le join public.profiles rp on rp.id=le.resident_id join public.profiles ap on ap.id=le.assessor_id
  where le.activity_category='manual_intervention' and le.senior_status='approved' and le.assessor_status='pending'

  union all
  -- Conferences go directly to assessor.
  select 'logbook:'||le.id::text||':conference','Conference approval',le.resident_id,rp.display_name,
    coalesce(le.title,'Conference'),le.assessor_id,ap.display_name,'Assessor',coalesce(le.created_at,le.activity_date::timestamptz),
    (select pm.id from public.private_messages pm where pm.logbook_entry_id=le.id and pm.receiver_id=le.assessor_id and pm.subject like 'Logbook approval request%' order by pm.created_at desc limit 1)
  from public.resident_logbook_entries le join public.profiles rp on rp.id=le.resident_id join public.profiles ap on ap.id=le.assessor_id
  where le.activity_category='conference' and le.assessor_status='pending'

  union all
  -- Current logbook reconsideration.
  select 'logbook-rec:'||lr.id::text,'Logbook reconsideration',lr.resident_id,rp.display_name,
    coalesce(le.procedure_name,le.title,'Logbook activity'),lr.reviewer_id,rv.display_name,
    case when rv.role::text='resident' then 'Senior resident' else initcap(rv.role::text) end,lr.created_at,lr.request_message_id
  from public.logbook_reconsiderations lr join public.profiles rp on rp.id=lr.resident_id join public.profiles rv on rv.id=lr.reviewer_id
  join public.resident_logbook_entries le on le.id=lr.entry_id where lr.status='requested'

  union all
  -- Review reconsideration.
  select 'review-rec:'||r.id::text,'Review reconsideration',r.resident_id,rp.display_name,
    initcap(r.category)||' review',r.observer_id,op.display_name,initcap(op.role::text),r.reconsideration_requested_at,
    (select l.message_id from public.review_message_links_v1051 l where l.review_id=r.id::text and l.recipient_id=r.observer_id and l.purpose='reconsideration_requested' order by l.created_at desc limit 1)
  from public.observer_reviews r join public.profiles rp on rp.id=r.resident_id join public.profiles op on op.id=r.observer_id
  where r.reconsideration_status='requested' and r.reconsideration_requested_at is not null

  union all
  -- Prior Experience: the two senior residents.
  select 'prior-senior:'||sr.id::text,'Prior Experience · senior verification',l.resident_id,rp.display_name,
    'Prior Experience Logbook',sr.senior_id,sp.display_name,'Senior resident',sr.created_at,
    (select ml.message_id from public.prior_experience_request_message_links_v1069 ml where ml.request_kind='senior' and ml.review_id=sr.id limit 1)
  from public.prior_experience_senior_reviews sr join public.prior_experience_logbooks l on l.id=sr.logbook_id
  join public.profiles rp on rp.id=l.resident_id join public.profiles sp on sp.id=sr.senior_id where sr.status='pending'

  union all
  -- Prior Experience: exact junior/older assessor signature.
  select 'prior-assessor:'||v.id::text,'Prior Experience · assessor signature',l.resident_id,rp.display_name,
    v.scope_name||' · '||initcap(v.assessor_level)||' assessor',v.assessor_id,ap.display_name,'Assessor',v.created_at,
    (select ml.message_id from public.prior_experience_request_message_links_v1069 ml where ml.request_kind='scope_verification' and ml.review_id=v.id limit 1)
  from public.prior_experience_scope_verifications v join public.prior_experience_logbooks l on l.id=v.logbook_id
  join public.profiles rp on rp.id=l.resident_id join public.profiles ap on ap.id=v.assessor_id where v.status='pending'

  union all
  -- Prior Experience reconsideration.
  select 'prior-rec:'||r.id::text,'Prior Experience · reconsideration',l.resident_id,rp.display_name,
    coalesce(r.scope_name,'Senior verification'),r.reviewer_id,rv.display_name,
    case when rv.role::text='resident' then 'Senior resident' else initcap(rv.role::text) end,r.created_at,
    (select ml.message_id from public.prior_experience_request_message_links_v1069 ml where ml.request_kind='reconsideration' and ml.review_id=r.id limit 1)
  from public.prior_experience_reconsiderations r join public.prior_experience_logbooks l on l.id=r.logbook_id
  join public.profiles rp on rp.id=l.resident_id join public.profiles rv on rv.id=r.reviewer_id where r.status='requested';
$$;
revoke all on function public._pending_request_rows_v1069() from public,anon,authenticated;

create or replace function public.process_pending_requests_v1069()
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  v_row record; v_count integer:=0; v_owner uuid; v_message_id bigint; v_body text; v_claimed timestamptz;
begin
  select p.id into v_owner from public.profiles p where p.role::text='owner' and p.is_active=true order by p.created_at nulls last limit 1;
  for v_row in select * from public._pending_request_rows_v1069()
  loop
    insert into public.workflow_request_reminder_state_v1069(request_key,original_message_id,last_pending_seen_at)
    values(v_row.request_key,v_row.original_message_id,now())
    on conflict(request_key) do update set original_message_id=coalesce(excluded.original_message_id,workflow_request_reminder_state_v1069.original_message_id),last_pending_seen_at=now();

    if now() >= v_row.issued_at + interval '48 hours' then
      v_claimed:=null;
      update public.workflow_request_reminder_state_v1069
         set reminded_at=now()
       where request_key=v_row.request_key and reminded_at is null
       returning reminded_at into v_claimed;
      if v_claimed is not null then
        v_body:=E'\n\n⏰ Automatic reminder after 48 hours\nThis request is still waiting for your decision. Please open the relevant request and approve/reject it.';
        if v_row.original_message_id is not null then
          update public.private_messages set body=coalesce(body,'')||v_body,read_at=null where id=v_row.original_message_id;
          v_message_id:=v_row.original_message_id;
        else
          insert into public.private_messages(sender_id,receiver_id,subject,body)
          values(coalesce(v_owner,v_row.sender_id),v_row.reviewer_id,'48-hour request reminder',
            'Automatic reminder · '||v_row.topic||E'\nSender: '||v_row.sender_name||E'\nThis request has been waiting for more than 48 hours. Please finalize it.')
          returning id into v_message_id;
        end if;
        update public.workflow_request_reminder_state_v1069 set original_message_id=coalesce(original_message_id,v_message_id) where request_key=v_row.request_key;
        v_count:=v_count+1;
      end if;
    end if;
  end loop;
  return v_count;
end;
$$;
revoke all on function public.process_pending_requests_v1069() from public,anon;
grant execute on function public.process_pending_requests_v1069() to authenticated;

create or replace function public.owner_pending_requests_v1069()
returns table(
  request_key text,request_type text,sender_name text,topic text,reviewer_name text,reviewer_role text,issued_at timestamptz,
  age_hours numeric,reminded_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then raise exception 'Owner access required'; end if;
  perform public.process_pending_requests_v1069();
  return query
  select r.request_key,r.request_type,r.sender_name,r.topic,r.reviewer_name,r.reviewer_role,r.issued_at,
    round((extract(epoch from (now()-r.issued_at))/3600.0)::numeric,1),st.reminded_at
  from public._pending_request_rows_v1069() r
  left join public.workflow_request_reminder_state_v1069 st on st.request_key=r.request_key
  order by r.issued_at;
end;
$$;
revoke all on function public.owner_pending_requests_v1069() from public,anon;
grant execute on function public.owner_pending_requests_v1069() to authenticated;

-- True automatic hourly execution when pg_cron is available in the Supabase project.
-- Dynamic SQL keeps the migration safe even if the extension is unavailable.
do $do$
declare v_job bigint;
begin
  begin
    execute 'create extension if not exists pg_cron';
  exception when others then
    raise notice 'pg_cron could not be enabled automatically; frontend activity will still process overdue reminders.';
  end;
  if exists(select 1 from pg_extension where extname='pg_cron') then
    for v_job in execute 'select jobid from cron.job where jobname=''resident-training-pending-reminders-v1069''' loop
      execute format('select cron.unschedule(%s)',v_job);
    end loop;
    execute $$select cron.schedule('resident-training-pending-reminders-v1069','0 * * * *','select public.process_pending_requests_v1069();')$$;
  end if;
exception when others then
  raise notice 'Could not schedule pg_cron reminder job: %',sqlerrm;
end $do$;

commit;
