-- Resident Training & Assessment v1.0.71
-- Residents Directory + Reviews & Penalties disciplinary workflow.
-- Run after the current v1.0.70 database repair/current schema.

begin;

-- ============================================================================
-- 1) CONFIGURABLE PENALTY CATALOGUE
-- ============================================================================
create table if not exists public.penalty_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 10,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.penalty_problems (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.penalty_categories(id),
  name text not null,
  sort_order integer not null default 10,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(category_id,name)
);

create table if not exists public.penalty_punishments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 10,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.penalty_categories(name,sort_order)
values ('Medical error',10),('Attitude and behaviour',20)
on conflict(name) do nothing;

insert into public.penalty_problems(category_id,name,sort_order)
select c.id,x.name,x.sort_order
from public.penalty_categories c
join (values
  ('Medical error','Diagnostic / clinical judgment',10),
  ('Medical error','Medication / prescription error',20),
  ('Medical error','Procedure / technical error',30),
  ('Medical error','Documentation / communication error',40),
  ('Medical error','Other medical error',90),
  ('Attitude and behaviour','Professionalism',10),
  ('Attitude and behaviour','Respect / communication',20),
  ('Attitude and behaviour','Attendance / punctuality',30),
  ('Attitude and behaviour','Teamwork',40),
  ('Attitude and behaviour','Failure to follow instructions',50),
  ('Attitude and behaviour','Other attitude / behaviour concern',90)
) as x(category_name,name,sort_order) on x.category_name=c.name
on conflict(category_id,name) do nothing;

insert into public.penalty_punishments(name,sort_order)
values
 ('Written warning',10),
 ('Formal counselling / remedial plan',20),
 ('Supervised remedial activity',30),
 ('Temporary restriction of specified activity',40),
 ('Other owner-defined action',90)
on conflict(name) do nothing;

-- ============================================================================
-- 2) PENALTY + COMPLAINT / APPEAL RECORDS
-- ============================================================================
create table if not exists public.resident_penalties (
  id bigint generated by default as identity primary key,
  resident_id uuid not null references public.profiles(id),
  issued_by uuid not null references public.profiles(id),
  category_id bigint not null references public.penalty_categories(id),
  problem_id bigint not null references public.penalty_problems(id),
  punishment_id bigint not null references public.penalty_punishments(id),
  category_label text not null,
  problem_label text not null,
  punishment_label text not null,
  details text not null,
  status text not null default 'pending_owner',
  owner_decision_note text,
  owner_decided_at timestamptz,
  complaint_text text,
  complained_at timestamptz,
  appeal_owner_decision text,
  appeal_owner_note text,
  appeal_owner_decided_at timestamptz,
  appeal_finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint resident_penalties_status_check check (status in (
    'pending_owner','approved','rejected','appeal_pending','appeal_upheld','appeal_overturned'
  )),
  constraint resident_penalties_appeal_owner_check check (appeal_owner_decision is null or appeal_owner_decision in ('uphold','overturn')),
  constraint resident_penalties_not_self_check check (resident_id <> issued_by)
);

create table if not exists public.penalty_appeal_reviewers (
  penalty_id bigint not null references public.resident_penalties(id) on delete cascade,
  slot smallint not null,
  assessor_id uuid not null references public.profiles(id),
  decision text,
  note text,
  decided_at timestamptz,
  assigned_at timestamptz not null default now(),
  assigned_by uuid references public.profiles(id),
  primary key(penalty_id,slot),
  unique(penalty_id,assessor_id),
  constraint penalty_appeal_reviewers_slot_check check (slot in (1,2)),
  constraint penalty_appeal_reviewers_decision_check check (decision is null or decision in ('uphold','overturn'))
);

create index if not exists resident_penalties_resident_idx on public.resident_penalties(resident_id,status,created_at desc);
create index if not exists resident_penalties_issuer_idx on public.resident_penalties(issued_by,created_at desc);
create index if not exists penalty_appeal_reviewer_queue_idx on public.penalty_appeal_reviewers(assessor_id,decision,assigned_at);

alter table public.penalty_categories enable row level security;
alter table public.penalty_problems enable row level security;
alter table public.penalty_punishments enable row level security;
alter table public.resident_penalties enable row level security;
alter table public.penalty_appeal_reviewers enable row level security;

revoke all on public.penalty_categories from public,anon,authenticated;
revoke all on public.penalty_problems from public,anon,authenticated;
revoke all on public.penalty_punishments from public,anon,authenticated;
revoke all on public.resident_penalties from public,anon,authenticated;
revoke all on public.penalty_appeal_reviewers from public,anon,authenticated;

-- ============================================================================
-- 3) COMMON HELPERS
-- ============================================================================
create or replace function public._owner_id_v1071()
returns uuid
language sql
stable
security definer
set search_path=public
as $$
  select p.id from public.profiles p
  where p.role::text='owner' and p.is_active=true
  order by p.created_at nulls last limit 1;
$$;
revoke all on function public._owner_id_v1071() from public,anon,authenticated;

create or replace function public._require_owner_v1071()
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='owner' and p.is_active=true) then
    raise exception 'Owner access required';
  end if;
end;
$$;
revoke all on function public._require_owner_v1071() from public,anon,authenticated;

-- ============================================================================
-- 4) RESIDENTS DIRECTORY
-- ============================================================================
create or replace function public.get_resident_directory_v1071()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_role text;
begin
  select p.role::text into v_role from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role not in ('resident','assessor','owner') then raise exception 'Directory access is limited to residents, assessors and the Program Owner'; end if;
  return query
  select jsonb_build_object(
    'id',p.id,
    'display_name',p.display_name,
    'username',p.username,
    'residency_year',p.residency_year,
    'avatar_url',p.avatar_url,
    'email',case when v_role in ('assessor','owner') then p.email else null end,
    'whatsapp',case when v_role in ('assessor','owner') then p.whatsapp else null end
  )
  from public.profiles p
  where p.role::text='resident' and p.is_active=true
  order by p.residency_year,p.display_name;
end;
$$;
revoke all on function public.get_resident_directory_v1071() from public,anon;
grant execute on function public.get_resident_directory_v1071() to authenticated;

-- ============================================================================
-- 5) PENALTY CONFIG + ELIGIBLE TARGETS
-- ============================================================================
create or replace function public.get_penalty_config_v1071()
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_role text;
begin
  select p.role::text into v_role from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role is null then raise exception 'Active account required'; end if;
  return jsonb_build_object(
    'categories',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'sort_order',c.sort_order,'is_active',c.is_active) order by c.sort_order,c.name) from public.penalty_categories c where c.is_active=true or v_role='owner'),'[]'::jsonb),
    'problems',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'category_id',x.category_id,'name',x.name,'sort_order',x.sort_order,'is_active',x.is_active) order by x.category_id,x.sort_order,x.name) from public.penalty_problems x where x.is_active=true or v_role='owner'),'[]'::jsonb),
    'punishments',coalesce((select jsonb_agg(jsonb_build_object('id',q.id,'name',q.name,'sort_order',q.sort_order,'is_active',q.is_active) order by q.sort_order,q.name) from public.penalty_punishments q where q.is_active=true or v_role='owner'),'[]'::jsonb)
  );
end;
$$;
revoke all on function public.get_penalty_config_v1071() from public,anon;
grant execute on function public.get_penalty_config_v1071() to authenticated;

create or replace function public.get_penalty_targets_v1071()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_role text; v_year integer;
begin
  select p.role::text,p.residency_year into v_role,v_year from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role='assessor' then
    return query select jsonb_build_object('id',p.id,'display_name',p.display_name,'residency_year',p.residency_year,'avatar_url',p.avatar_url)
      from public.profiles p where p.role::text='resident' and p.is_active=true order by p.residency_year,p.display_name;
  elsif v_role='resident' and coalesce(v_year,0)>1 then
    return query select jsonb_build_object('id',p.id,'display_name',p.display_name,'residency_year',p.residency_year,'avatar_url',p.avatar_url)
      from public.profiles p where p.role::text='resident' and p.is_active=true and p.residency_year < v_year order by p.residency_year,p.display_name;
  else
    return;
  end if;
end;
$$;
revoke all on function public.get_penalty_targets_v1071() from public,anon;
grant execute on function public.get_penalty_targets_v1071() to authenticated;

-- ============================================================================
-- 6) CREATE PENALTY
-- ============================================================================
create or replace function public.create_resident_penalty_v1071(
  p_resident_id uuid,
  p_category_id bigint,
  p_problem_id bigint,
  p_punishment_id bigint,
  p_details text
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_role text; v_year integer; v_target_year integer; v_id bigint;
  v_category text; v_problem text; v_punishment text; v_owner uuid; v_issuer text; v_target text;
begin
  select p.role::text,p.residency_year,p.display_name into v_role,v_year,v_issuer
  from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role is null then raise exception 'Active account required'; end if;
  select p.residency_year,p.display_name into v_target_year,v_target from public.profiles p
  where p.id=p_resident_id and p.role::text='resident' and p.is_active=true;
  if v_target_year is null then raise exception 'Resident not found'; end if;
  if p_resident_id=auth.uid() then raise exception 'You cannot sign a penalty against yourself'; end if;
  if v_role='resident' then
    if coalesce(v_year,0)<=1 then raise exception 'Year 1 residents cannot sign penalties'; end if;
    if v_target_year >= v_year then raise exception 'Residents may sign penalties only against residents in a lower residency year'; end if;
  elsif v_role<>'assessor' then
    raise exception 'Only eligible senior residents and assessors can sign penalties';
  end if;
  if char_length(trim(coalesce(p_details,'')))<2 then raise exception 'Write a short description of the incident'; end if;

  select c.name into v_category from public.penalty_categories c where c.id=p_category_id and c.is_active=true;
  select x.name into v_problem from public.penalty_problems x where x.id=p_problem_id and x.category_id=p_category_id and x.is_active=true;
  select q.name into v_punishment from public.penalty_punishments q where q.id=p_punishment_id and q.is_active=true;
  if v_category is null or v_problem is null or v_punishment is null then raise exception 'Choose valid active penalty options'; end if;

  insert into public.resident_penalties(resident_id,issued_by,category_id,problem_id,punishment_id,category_label,problem_label,punishment_label,details)
  values(p_resident_id,auth.uid(),p_category_id,p_problem_id,p_punishment_id,v_category,v_problem,v_punishment,trim(p_details))
  returning id into v_id;

  v_owner:=public._owner_id_v1071();
  if v_owner is null then raise exception 'Active Program Owner required'; end if;
  insert into public.private_messages(sender_id,receiver_id,subject,body)
  values(auth.uid(),v_owner,'Penalty awaiting approval',
    'Resident: '||coalesce(v_target,'Resident')||E'\nSigned by: '||coalesce(v_issuer,'Reviewer')||E'\nCategory: '||v_category||E'\nProblem: '||v_problem||E'\nProposed punishment: '||v_punishment||E'\nDetails: '||trim(p_details)||E'\nOpen Reviews & penalties to approve or reject it.');
  return v_id;
end;
$$;
revoke all on function public.create_resident_penalty_v1071(uuid,bigint,bigint,bigint,text) from public,anon;
grant execute on function public.create_resident_penalty_v1071(uuid,bigint,bigint,bigint,text) to authenticated;

-- ============================================================================
-- 7) PENALTY VISIBILITY
-- ============================================================================
create or replace function public._penalty_json_v1071(p public.resident_penalties)
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'id',p.id,'resident_id',p.resident_id,'resident_name',rp.display_name,'residency_year',rp.residency_year,
    'issued_by',p.issued_by,'issuer_name',ip.display_name,'issuer_role',ip.role::text,'issuer_year',ip.residency_year,
    'category_id',p.category_id,'problem_id',p.problem_id,'punishment_id',p.punishment_id,
    'category',p.category_label,'problem',p.problem_label,'punishment',p.punishment_label,'details',p.details,
    'status',p.status,'owner_note',p.owner_decision_note,'owner_decided_at',p.owner_decided_at,
    'complaint_text',p.complaint_text,'complained_at',p.complained_at,
    'appeal_owner_decision',p.appeal_owner_decision,'appeal_owner_note',p.appeal_owner_note,
    'created_at',p.created_at,'updated_at',p.updated_at,
    'appeal_reviewers',coalesce((select jsonb_agg(jsonb_build_object('slot',ar.slot,'assessor_id',ar.assessor_id,'assessor_name',ap.display_name,'decision',ar.decision,'note',ar.note,'decided_at',ar.decided_at) order by ar.slot) from public.penalty_appeal_reviewers ar join public.profiles ap on ap.id=ar.assessor_id where ar.penalty_id=p.id),'[]'::jsonb)
  )
  from public.profiles rp join public.profiles ip on ip.id=p.issued_by where rp.id=p.resident_id;
$$;
revoke all on function public._penalty_json_v1071(public.resident_penalties) from public,anon,authenticated;

create or replace function public.get_penalties_for_me_v1071()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_role text;
begin
  select p.role::text into v_role from public.profiles p where p.id=auth.uid() and p.is_active=true;
  if v_role is null then raise exception 'Active account required'; end if;
  if v_role='owner' then
    return query select public._penalty_json_v1071(p) from public.resident_penalties p order by p.created_at desc;
  elsif v_role='resident' then
    return query select public._penalty_json_v1071(p) from public.resident_penalties p
      where p.issued_by=auth.uid()
         or (p.resident_id=auth.uid() and p.status in ('approved','appeal_pending','appeal_upheld','appeal_overturned'))
      order by p.created_at desc;
  elsif v_role='assessor' then
    return query select public._penalty_json_v1071(p) from public.resident_penalties p
      where p.issued_by=auth.uid() or exists(select 1 from public.penalty_appeal_reviewers ar where ar.penalty_id=p.id and ar.assessor_id=auth.uid())
      order by p.created_at desc;
  else return;
  end if;
end;
$$;
revoke all on function public.get_penalties_for_me_v1071() from public,anon;
grant execute on function public.get_penalties_for_me_v1071() to authenticated;

create or replace function public.get_penalty_admin_rows_v1071()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  perform public._require_owner_v1071();
  return query select public._penalty_json_v1071(p) from public.resident_penalties p order by p.created_at desc;
end;
$$;
revoke all on function public.get_penalty_admin_rows_v1071() from public,anon;
grant execute on function public.get_penalty_admin_rows_v1071() to authenticated;

-- ============================================================================
-- 8) OWNER INITIAL APPROVAL / REJECTION
-- ============================================================================
create or replace function public.owner_decide_penalty_v1071(p_penalty_id bigint,p_decision text,p_note text default null)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare v public.resident_penalties%rowtype; v_owner uuid; v_owner_name text; v_target text; v_issuer text;
begin
  perform public._require_owner_v1071();
  if p_decision not in ('approved','rejected') then raise exception 'Decision must be approved or rejected'; end if;
  select * into v from public.resident_penalties where id=p_penalty_id for update;
  if not found then raise exception 'Penalty not found'; end if;
  if v.status<>'pending_owner' then raise exception 'This penalty has already been decided'; end if;
  update public.resident_penalties set status=p_decision,owner_decision_note=nullif(trim(coalesce(p_note,'')),''),owner_decided_at=now(),updated_at=now() where id=p_penalty_id;
  select p.display_name into v_target from public.profiles p where p.id=v.resident_id;
  select p.display_name into v_issuer from public.profiles p where p.id=v.issued_by;
  select p.id,p.display_name into v_owner,v_owner_name from public.profiles p where p.id=auth.uid();
  if p_decision='approved' then
    insert into public.private_messages(sender_id,receiver_id,subject,body) values(v_owner,v.resident_id,'Penalty approved',
      'A penalty was approved by the Program Owner.'||E'\nCategory: '||v.category_label||E'\nProblem: '||v.problem_label||E'\nPunishment: '||v.punishment_label||E'\nDetails: '||v.details||E'\nSigned by: '||coalesce(v_issuer,'Reviewer')||case when nullif(trim(coalesce(p_note,'')),'') is not null then E'\nOwner note: '||trim(p_note) else '' end||E'\nYou may complain from Reviews & penalties.');
    insert into public.private_messages(sender_id,receiver_id,subject,body) values(v_owner,v.issued_by,'Penalty approved by Program Owner','Your penalty for '||coalesce(v_target,'Resident')||' was approved.');
  else
    insert into public.private_messages(sender_id,receiver_id,subject,body) values(v_owner,v.issued_by,'Penalty rejected by Program Owner','Your proposed penalty for '||coalesce(v_target,'Resident')||' was rejected.'||case when nullif(trim(coalesce(p_note,'')),'') is not null then E'\nOwner note: '||trim(p_note) else '' end);
  end if;
  return p_decision;
end;
$$;
revoke all on function public.owner_decide_penalty_v1071(bigint,text,text) from public,anon;
grant execute on function public.owner_decide_penalty_v1071(bigint,text,text) to authenticated;

-- ============================================================================
-- 9) RESIDENT COMPLAINT + NEUTRAL PANEL
-- ============================================================================
create or replace function public.resident_complain_penalty_v1071(p_penalty_id bigint,p_complaint text)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v public.resident_penalties%rowtype; v_owner uuid; v_name text;
begin
  select * into v from public.resident_penalties where id=p_penalty_id and resident_id=auth.uid() for update;
  if not found then raise exception 'Penalty not found'; end if;
  if v.status<>'approved' then raise exception 'Only an approved penalty can be complained against'; end if;
  if char_length(trim(coalesce(p_complaint,'')))<2 then raise exception 'Write your complaint'; end if;
  update public.resident_penalties set status='appeal_pending',complaint_text=trim(p_complaint),complained_at=now(),appeal_owner_decision=null,appeal_owner_note=null,appeal_owner_decided_at=null,appeal_finalized_at=null,updated_at=now() where id=p_penalty_id;
  delete from public.penalty_appeal_reviewers where penalty_id=p_penalty_id;
  v_owner:=public._owner_id_v1071();
  select p.display_name into v_name from public.profiles p where p.id=auth.uid();
  insert into public.private_messages(sender_id,receiver_id,subject,body) values(auth.uid(),v_owner,'Penalty complaint',
    'Resident: '||coalesce(v_name,'Resident')||E'\nPenalty: '||v.category_label||' · '||v.problem_label||E'\nPunishment: '||v.punishment_label||E'\nComplaint: '||trim(p_complaint)||E'\nChoose two neutral assessors in Reviews & penalties.');
end;
$$;
revoke all on function public.resident_complain_penalty_v1071(bigint,text) from public,anon;
grant execute on function public.resident_complain_penalty_v1071(bigint,text) to authenticated;

create or replace function public.owner_assign_penalty_appeal_reviewers_v1071(p_penalty_id bigint,p_assessor_1 uuid,p_assessor_2 uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v public.resident_penalties%rowtype; v_owner uuid; v_target text; aid uuid; aname text;
begin
  perform public._require_owner_v1071();
  if p_assessor_1=p_assessor_2 then raise exception 'Choose two different neutral assessors'; end if;
  select * into v from public.resident_penalties where id=p_penalty_id for update;
  if not found or v.status<>'appeal_pending' then raise exception 'This penalty has no open complaint'; end if;
  if p_assessor_1=v.issued_by or p_assessor_2=v.issued_by then raise exception 'The original penalty issuer cannot act as a neutral assessor'; end if;
  if not exists(select 1 from public.profiles p where p.id=p_assessor_1 and p.role::text='assessor' and p.is_active=true) or
     not exists(select 1 from public.profiles p where p.id=p_assessor_2 and p.role::text='assessor' and p.is_active=true) then
    raise exception 'Both neutral reviewers must be active assessors';
  end if;
  delete from public.penalty_appeal_reviewers where penalty_id=p_penalty_id;
  insert into public.penalty_appeal_reviewers(penalty_id,slot,assessor_id,assigned_by) values(p_penalty_id,1,p_assessor_1,auth.uid()),(p_penalty_id,2,p_assessor_2,auth.uid());
  select p.display_name into v_target from public.profiles p where p.id=v.resident_id;
  v_owner:=auth.uid();
  for aid,aname in select p.id,p.display_name from public.profiles p where p.id in (p_assessor_1,p_assessor_2)
  loop
    insert into public.private_messages(sender_id,receiver_id,subject,body) values(v_owner,aid,'Neutral penalty review assigned',
      'Resident: '||coalesce(v_target,'Resident')||E'\nCategory: '||v.category_label||E'\nProblem: '||v.problem_label||E'\nPunishment: '||v.punishment_label||E'\nComplaint: '||coalesce(v.complaint_text,'—')||E'\nOpen Reviews & penalties to uphold or overturn the penalty.');
  end loop;
end;
$$;
revoke all on function public.owner_assign_penalty_appeal_reviewers_v1071(bigint,uuid,uuid) from public,anon;
grant execute on function public.owner_assign_penalty_appeal_reviewers_v1071(bigint,uuid,uuid) to authenticated;

create or replace function public._recalculate_penalty_appeal_v1071(p_penalty_id bigint)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare v public.resident_penalties%rowtype; v_count integer; v_uphold integer; v_overturn integer; v_final text; v_owner uuid; v_target text; v_issuer text;
begin
  select * into v from public.resident_penalties where id=p_penalty_id for update;
  if not found or v.status<>'appeal_pending' then return coalesce(v.status,'missing'); end if;
  if v.appeal_owner_decision is null then return 'appeal_pending'; end if;
  select count(*) filter(where decision is not null),count(*) filter(where decision='uphold'),count(*) filter(where decision='overturn') into v_count,v_uphold,v_overturn from public.penalty_appeal_reviewers where penalty_id=p_penalty_id;
  if v_count<2 then return 'appeal_pending'; end if;
  if v.appeal_owner_decision='uphold' then v_uphold:=v_uphold+1; else v_overturn:=v_overturn+1; end if;
  v_final:=case when v_uphold>=2 then 'appeal_upheld' else 'appeal_overturned' end;
  update public.resident_penalties set status=v_final,appeal_finalized_at=now(),updated_at=now() where id=p_penalty_id;
  v_owner:=public._owner_id_v1071();
  select p.display_name into v_target from public.profiles p where p.id=v.resident_id;
  select p.display_name into v_issuer from public.profiles p where p.id=v.issued_by;
  insert into public.private_messages(sender_id,receiver_id,subject,body) values(v_owner,v.resident_id,
    case when v_final='appeal_upheld' then 'Penalty complaint decision · penalty upheld' else 'Penalty complaint decision · penalty cancelled' end,
    case when v_final='appeal_upheld' then 'The neutral review panel upheld the penalty.' else 'The neutral review panel overturned the penalty. It is no longer an active disciplinary penalty.' end);
  insert into public.private_messages(sender_id,receiver_id,subject,body) values(v_owner,v.issued_by,
    case when v_final='appeal_upheld' then 'Penalty appeal upheld' else 'Penalty appeal overturned' end,
    'Penalty for '||coalesce(v_target,'Resident')||': '||case when v_final='appeal_upheld' then 'upheld by the appeal panel.' else 'overturned by the appeal panel.' end);
  return v_final;
end;
$$;
revoke all on function public._recalculate_penalty_appeal_v1071(bigint) from public,anon,authenticated;

create or replace function public.assessor_vote_penalty_appeal_v1071(p_penalty_id bigint,p_decision text,p_note text default null)
returns text
language plpgsql
security definer
set search_path=public
as $$
begin
  if p_decision not in ('uphold','overturn') then raise exception 'Choose uphold or overturn'; end if;
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='assessor' and p.is_active=true) then raise exception 'Assessor access required'; end if;
  update public.penalty_appeal_reviewers set decision=p_decision,note=nullif(trim(coalesce(p_note,'')),''),decided_at=now()
  where penalty_id=p_penalty_id and assessor_id=auth.uid() and decision is null;
  if not found then raise exception 'No pending neutral-review assignment was found'; end if;
  return public._recalculate_penalty_appeal_v1071(p_penalty_id);
end;
$$;
revoke all on function public.assessor_vote_penalty_appeal_v1071(bigint,text,text) from public,anon;
grant execute on function public.assessor_vote_penalty_appeal_v1071(bigint,text,text) to authenticated;

create or replace function public.owner_vote_penalty_appeal_v1071(p_penalty_id bigint,p_decision text,p_note text default null)
returns text
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public._require_owner_v1071();
  if p_decision not in ('uphold','overturn') then raise exception 'Choose uphold or overturn'; end if;
  update public.resident_penalties set appeal_owner_decision=p_decision,appeal_owner_note=nullif(trim(coalesce(p_note,'')),''),appeal_owner_decided_at=now(),updated_at=now()
  where id=p_penalty_id and status='appeal_pending';
  if not found then raise exception 'No open penalty complaint was found'; end if;
  return public._recalculate_penalty_appeal_v1071(p_penalty_id);
end;
$$;
revoke all on function public.owner_vote_penalty_appeal_v1071(bigint,text,text) from public,anon;
grant execute on function public.owner_vote_penalty_appeal_v1071(bigint,text,text) to authenticated;

create or replace function public.get_my_penalty_appeals_v1071()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text='assessor' and p.is_active=true) then return; end if;
  return query
  select public._penalty_json_v1071(p) || jsonb_build_object('my_appeal_decision',ar.decision,'my_appeal_note',ar.note,'my_slot',ar.slot)
  from public.penalty_appeal_reviewers ar join public.resident_penalties p on p.id=ar.penalty_id
  where ar.assessor_id=auth.uid() order by ar.assigned_at desc;
end;
$$;
revoke all on function public.get_my_penalty_appeals_v1071() from public,anon;
grant execute on function public.get_my_penalty_appeals_v1071() to authenticated;

-- ============================================================================
-- 10) ASSESSMENT VISIBILITY
-- ============================================================================
create or replace function public.get_resident_penalties_for_assessment_v1071(p_resident_id uuid)
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_role text; v_year integer;
begin
  select p.role::text into v_role from public.profiles p where p.id=auth.uid() and p.is_active=true;
  select p.residency_year into v_year from public.profiles p where p.id=p_resident_id and p.role::text='resident';
  if v_year is null then raise exception 'Resident not found'; end if;
  if v_role='owner' then null;
  elsif v_role='assessor' then
    if not exists(select 1 from public.assessor_year_assignments a where a.assessor_id=auth.uid() and a.residency_year=v_year and a.is_active=true) then raise exception 'This resident is not in your assigned assessment cohorts'; end if;
  else raise exception 'Assessment penalty access requires assigned assessor or Owner';
  end if;
  return query select public._penalty_json_v1071(p) from public.resident_penalties p
    where p.resident_id=p_resident_id and p.status in ('approved','appeal_pending','appeal_upheld')
    order by p.created_at desc;
end;
$$;
revoke all on function public.get_resident_penalties_for_assessment_v1071(uuid) from public,anon;
grant execute on function public.get_resident_penalties_for_assessment_v1071(uuid) to authenticated;

-- ============================================================================
-- 11) OWNER EDITABLE DROPDOWN CATALOGUE
-- ============================================================================
create or replace function public.owner_save_penalty_option_v1071(
  p_kind text,
  p_id bigint,
  p_name text,
  p_category_id bigint default null,
  p_sort_order integer default 10
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  perform public._require_owner_v1071();
  if char_length(trim(coalesce(p_name,'')))<2 then raise exception 'Name is required'; end if;
  if p_kind='category' then
    if p_id is null then insert into public.penalty_categories(name,sort_order) values(trim(p_name),coalesce(p_sort_order,10)) returning id into v_id;
    else update public.penalty_categories set name=trim(p_name),sort_order=coalesce(p_sort_order,10),is_active=true,updated_at=now() where id=p_id returning id into v_id; end if;
  elsif p_kind='problem' then
    if p_category_id is null or not exists(select 1 from public.penalty_categories c where c.id=p_category_id) then raise exception 'Choose a category'; end if;
    if p_id is null then insert into public.penalty_problems(category_id,name,sort_order) values(p_category_id,trim(p_name),coalesce(p_sort_order,10)) returning id into v_id;
    else update public.penalty_problems set category_id=p_category_id,name=trim(p_name),sort_order=coalesce(p_sort_order,10),is_active=true,updated_at=now() where id=p_id returning id into v_id; end if;
  elsif p_kind='punishment' then
    if p_id is null then insert into public.penalty_punishments(name,sort_order) values(trim(p_name),coalesce(p_sort_order,10)) returning id into v_id;
    else update public.penalty_punishments set name=trim(p_name),sort_order=coalesce(p_sort_order,10),is_active=true,updated_at=now() where id=p_id returning id into v_id; end if;
  else raise exception 'Unknown option type'; end if;
  if v_id is null then raise exception 'Option not found'; end if;
  return v_id;
end;
$$;
revoke all on function public.owner_save_penalty_option_v1071(text,bigint,text,bigint,integer) from public,anon;
grant execute on function public.owner_save_penalty_option_v1071(text,bigint,text,bigint,integer) to authenticated;

create or replace function public.owner_set_penalty_option_active_v1071(p_kind text,p_id bigint,p_active boolean)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public._require_owner_v1071();
  if p_kind='category' then update public.penalty_categories set is_active=p_active,updated_at=now() where id=p_id;
  elsif p_kind='problem' then update public.penalty_problems set is_active=p_active,updated_at=now() where id=p_id;
  elsif p_kind='punishment' then update public.penalty_punishments set is_active=p_active,updated_at=now() where id=p_id;
  else raise exception 'Unknown option type'; end if;
  if not found then raise exception 'Option not found'; end if;
end;
$$;
revoke all on function public.owner_set_penalty_option_active_v1071(text,bigint,boolean) from public,anon;
grant execute on function public.owner_set_penalty_option_active_v1071(text,bigint,boolean) to authenticated;

commit;
